### ISSUE TITLE
spirv-dis outputs error with spirv file generated by latest clspv

### ISSUE THREAD

**Issue by byzin** [google/clspv#1008]
Hi,

spirv-dis failed and outputs an error message with the spirv file generated by latest clspv (d295d0326d8ab189d0399cd416b6bd739bb45cb7).

kernel,
```
__kernel void testKernel(__global int* output)
{
  const uint index = get_global_linear_id();
  if (index == 0)
    output[0] = 0;
}
```
I compiled the kernel and tried spirv-dis,
```
clspv -cl-std=CLC++ -inline-entry-points -o spirv_test.spv spirv_test.cl
spirv-dis -o spirv_test.txt spirv_test.spv
```
and I got the following error message,
```
error: 89: Invalid instruction OpExtInst starting at word 386: expected no more operands after 7 words, but stated word count is 8.
```

Could you take a look at it? Thanks.

I tried it on Ubuntu 22.04 and used [Vulkan SDK 1.3.236.0](https://vulkan.lunarg.com/sdk/home#linux) for spirv-dis.

Here is the source code,
[spirv_test.zip](https://github.com/google/clspv/files/10481450/spirv_test.zip)

**Comment by alan-baker** [comment]
You'll need to use more recent SPIRV-Headers. See those pinned in deps.json.

**Comment by byzin** [comment]
I got it thanks! I'll try using new spirv-dis.
