### ISSUE TITLE
 Class template specialization vs inherited struct as kernel parameter

### ISSUE THREAD

**Issue by bmanga** [google/clspv#1053]
Hi, the following code:
```cpp
template <unsigned Size, class Ty> struct Vector {
    Ty data[Size] = {};
};

#ifdef USE_INHERITANCE
struct Vector2f : Vector<2, float> {};
#else
using Vector2f = Vector<2, float>;
#endif

kernel void k(global float *out, global Vector2f *in2) {
    auto index = get_global_id(0);
    out[index] = in2->data[0];
}
```
compiles only if `Vector2f` is a record declaration inheriting from the class template specialization. Using the class template specialization directly as a kernel parameter results in an error.

I don't think this limitation is intended.

godbolt link: https://godbolt.org/z/jxYEn1jYq

**Comment by rjodinchr** [comment]
As shown in the output of clspv in compiler-explorer:
```
error: '__global Vector2f *__private' (aka '__global Vector<2, float> *__private') cannot be used as the type of a kernel parameter
```

It seems that declaring `Vector2f`  with the `using` keyword makes it a `private` pointer. Private pointer cannot be a kernel parameter.

If there is an error, it feels like a `clang` error more than `clspv`.

**Comment by bmanga** [comment]
Hi @rjodinchr, thanks for the quick reply. The error persists also if you use the specialization directly as a kernel param, so I don't think it's the `using`'s fault:
```cpp
kernel void k(global float *out, global Vector<2, float> *in2) {
    auto index = get_global_id(0);
    out[index] = in2->data[0];
}
```
same error:
```
error: '__global Vector<2, float> *__private' cannot be used as the type of a kernel parameter
```

**Comment by rjodinchr** [comment]
Alright, but still this is something related with `clang` not `clspv` I believe.

**Comment by bmanga** [comment]
Yeah, seems to be the case: https://godbolt.org/z/5aMqvxoqT

Thanks, I'll raise this on the llvm side.
