### ISSUE TITLE
Assertion in BitcastUtils when compiling kernels used by x264

### ISSUE THREAD

**Issue by kpet** [google/clspv#1071]
Compiling the attached source file with the following command line:

```
clspv source.cl  -cl-single-precision-constant  -cl-kernel-arg-info   -fp16=0  -rewrite-packed-structs  -std430-ubo-layout  -decorate-nonuniform    -arch=spir  -spv-version=1.6  -max-pushconstant-size=256  -max-ubo-size=65536  -global-offset  -long-vector  -module-constants-in-storage-buffer  -cl-arm-non-uniform-work-group-size     -o compiled.spv
```

results in the following assertion being hit:

```
clspv: /mnt/work/repos/clvk/external/clspv/lib/BitcastUtils.cpp:375: void BitcastUtils::GroupScalarValuesIntoVector(llvm::IRBuilder<>&, llvm::SmallVector<llvm::Value*, 8>&, unsigned int): Assertion `Values.size() % NumElePerVec == 0' failed.
```

[source.txt](https://github.com/google/clspv/files/11174007/source.txt)

**Comment by rjodinchr** [comment]
I have had a first look at it.
The assertion is coming from the run of the ReplacePointerBitcastPass on the `parallel_sum` function.
What I don't understand is that we can see that this function is using the local `cache` variable from `mb_intra_cost_satd_8x8`. But when I look for where the `parallel_sum` function is called, I don't see any link with this variable.

Applying this patch:
```
diff --git a/lib/BitcastUtils.cpp b/lib/BitcastUtils.cpp
index fc497d32..fb3e5142 100644
--- a/lib/BitcastUtils.cpp
+++ b/lib/BitcastUtils.cpp
@@ -372,8 +372,10 @@ void GroupScalarValuesIntoVector(IRBuilder<> &Builder,
   Type *SrcTy = Values[0]->getType();
   assert(!SrcTy->isVectorTy() && !SrcTy->isArrayTy());
   VectorType *DstTy = FixedVectorType::get(SrcTy, NumElePerVec);
-  assert(Values.size() % NumElePerVec == 0);
   unsigned int NumVector = Values.size() / NumElePerVec;
+  if (Values.size() > NumElePerVec && Values.size() % NumElePerVec != 0) {
+    Values.resize(NumVector * NumElePerVec);
+  }
   for (unsigned i = 0; i < NumVector; i++) {
     unsigned idx = i * NumElePerVec;
     Value *Vec = PoisonValue::get(DstTy);
```
allows to avoid this assert.
It can also be done by changing the size of the `cache` variable: `local pixel cache[2388]`
It makes it a multiple of 4, avoid the above issue trying to bitcast the array of i8 to i32.

But after that we end up having another issue:
```
OpPtrAccessChain is not supported for this storage class
UNREACHABLE executed at /usr/local/google/home/rjodin/work/clvk/external/clspv/lib/SPIRVProducerPass.cpp:4928!
```
I've quickly tried to work around it, but I ended up having an issue with a phi node:
```
error: line 3668: OpPhi's result type <id> '2911[%_ptr_Function_uchar]' does not match incoming value <id> '2668[%2668]' type <id> '2655[%_ptr_Function__arr_uchar_uint_32]'.
  %3142 = OpPhi %_ptr_Function_uchar %3220 %3140 %2668 %2906
  ```

**Comment by kpet** [comment]
Thanks for having a look. I reported it so it's on people's radar but I think it's less important than https://github.com/google/clspv/issues/1067.
