### ISSUE TITLE
Error with nullptr checks

### ISSUE THREAD

**Issue by bmanga** [google/clspv#1077]
The following code fails with an assertion about "Attempting to get element type of opaque pointer" caused by the commented line.
```cpp
inline float loop(const float *data, unsigned num) {
    float res = 0;
    for (unsigned j = 0; j < num; ++j) {
        if (!data) break; // issue here. Ok if commented out.
        res += data[j];
    }
    return res;
}

kernel void k(global float* in, global float* out) {
    unsigned index = get_global_id(0);
    out[index] = loop(in, index);
}
```

godbolt link: https://godbolt.org/z/dWe1v4cYP

**Comment by rjodinchr** [comment]
As explained in the [doc](https://github.com/google/clspv/blob/main/docs/OpenCLCOnVulkan.md#pointers), this is due to an actual limitation. We cannot compare pointers right now.

But a lot of [work](https://github.com/google/clspv/issues/826) has been done by codeplay on behalf of Samsung to add support for physical addressing which should remove this restriction

**Comment by bmanga** [comment]
Hi @rjodinchr, thanks for your prompt replies :)

I opened this issue because if the `loop` fn takes data as a `global` pointer, clspv warns that pointer comparisons are only available if you specify spirv version 1.4 or above, and everything seems to work fine if you do.

The version I specified instead produces an `addrspacecast` instruction :
```llvm
%41 = addrspacecast ptr addrspace(4) null to ptr addrspace(1)
```
which I think clspv is not yet able to handle.

**Comment by rjodinchr** [comment]
`addrspace(4)` is the OpenCL generic address space, which is not supported.

I will look at why we don't have a more explicit error message.

**Comment by rjodinchr** [comment]
I found how to report an explicit message.

But as the support for generic address space is close to being complete, I will finish this implementation.
