### ISSUE TITLE
Incorrect code transform in simplify pointer bitcasts

### ISSUE THREAD

**Issue by alan-baker** [google/clspv#1115]
`test6` in `test/PointerCasts/opaque_trivial_casts.ll` produces an incorrect transformation.

It assumes that certain address spaces cannot have non-zero first index in the GEP. While SPIR-V cannot use PtrAccessChain in those address spaces, producing incorrect code is worse than invalid code.

**Comment by rjodinchr** [comment]
I agree, the test is wrong, I will fix it with [this commit](https://github.com/rjodinchr/clspv/commit/31d8e6ef87e28a70d588c636fe39265bea4d1bb0)
