### ISSUE TITLE
Why VK_KHR_variable_pointers are must have feature in Vulkan for supporting clspv

### ISSUE THREAD

**Issue by lygstate** [google/clspv#113]
I found my graphics card(GTX 860M) do not support for VK_KHR_variable_pointers feature.
And so it's do not support for spirv genearted by clspv.
So is that possible to getting VK_KHR_variable_pointers to be an optional feature?

**Comment by dneto0** [comment]
Vulkan normally has very restrictive rules about how you can address memory.  See "Logical addressing mode" in the SPIR-V spec.  But OpenCL has much more C-like semantics for pointers.  The "variable pointers" extension adds a small number of features to Vulkan's shader programming model that lets us compile *some* OpenCL C programs.  This is a very deep assumption by the clspv compiler, so it generates SPIR-V modules that always declare the need for the extension.

That being said, it looks like the GTX 860M has a Vulkan driver that does support the variable pointers extension.  See  https://developer.nvidia.com/vulkan-driver 
I suggest updating to the latest NVIDIA drivers.

**Comment by lygstate** [comment]
@dneto0 I also have a question, does any mobile phone(Android) support for VK_KHR_variable_pointers?

**Comment by msiglreith** [comment]
As I've just seen the topic, is there a complete list of features/places where `KHR_variable_pointers` is required? I'm just wondering what parts of OpenCL require this extension. I tried to reverse engineer the information from the code but it's difficult for me.

**Comment by sheredom** [comment]
There are basically two parts that I'll try and describe with pseudo-code:

```
int foo(global int* a) {
  // Any index that is non-zero or dynamic here requires variable pointers!
  return a[1];
}

void kernel bar(global int* a) {
  *a = foo(a);
}
```

And;

```
void kernel foo(global int* a, global int* b, bool which) {
  // We can't do this selection without variable pointers!
  global int* c = which ? b : a;

  *c = 42;
}
```

Both of these you _can_ workaround - the first one you could just inline any function when you see that pattern, the second you could create duplicate basic blocks from `c` onwards, one where `c` is `b`, the other where `c` is `a`. but the _sheer amount of code you'll be adding is monstrous in non-trivial cases_.
