### ISSUE TITLE
simple kernel causing vulkan validation error

### ISSUE THREAD

**Issue by eladmaimoni** [google/clspv#1164]
The following opencl kermel

```
__attribute__((reqd_work_group_size(16, 16, 1)))
__kernel void bgr_2_rgba(__global const uchar* input, uint2 dims, __write_only image2d_t out_image)
{
    const uint width = dims.x;
    const uint height = dims.y;

    const uint x = get_global_id(0);
    const uint y = get_global_id(1);
 
    if (x < width && y < height)
    {
        const uint idx = (y * width + x);
        const uchar3 bgr = vload3(idx, input);
        const float4 rgba = (float4)((float)bgr.z / 255.0f, (float)bgr.y / 255.0f, (float)bgr.x / 255.0f, 1.0f);
        write_imagef(out_image, (int2)((int)x, (int)y), rgba);
    }
}
```

compiled with `-spv-version=1.3` yields the following vulkan validation error:

```
Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x1e6062a7c00, type = VK_OBJECT_TYPE_DEVICE; | MessageID =
 0x6bbb14 | SPIR-V module not valid: Invalid instruction OpExtInst starting at word 456: expected no more operands after 7 words, but stated word count
 is 8.
```

The kernel seems to be working fine though. at least on my nvidia hardware.

[Link to compiler explorer](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:openclc,selection:(endColumn:1,endLineNumber:18,positionColumn:1,positionLineNumber:18,selectionStartColumn:1,selectionStartLineNumber:18,startColumn:1,startLineNumber:18),source:'__attribute__((reqd_work_group_size(16,+16,+1)))%0A__kernel+void+bgr_2_rgba(__global+const+uchar*+input,+uint2+dims,+__write_only+image2d_t+out_image)%0A%7B%0A%09const+uint+width+%3D+dims.x%3B%0A%09const+uint+height+%3D+dims.y%3B%0A%0A++++const+uint+x+%3D+get_global_id(0)%3B%0A++++const+uint+y+%3D+get_global_id(1)%3B%0A+%0A++++if+(x+%3C+width+%26%26+y+%3C+height)%0A++++%7B%0A++++++++const+uint+idx+%3D+(y+*+width+%2B+x)%3B%0A++++++++const+uchar3+bgr+%3D+vload3(idx,+input)%3B%0A++++++++const+float4+rgba+%3D+(float4)((float)bgr.z+/+255.0f,+(float)bgr.y+/+255.0f,+(float)bgr.x+/+255.0f,+1.0f)%3B%0A++++++++write_imagef(out_image,+(int2)((int)x,+(int)y),+rgba)%3B%0A++++%7D%0A%7D%0A'),l:'5',n:'0',o:'OpenCL+C+source+%231',t:'0')),k:53.25707341259033,l:'4',m:100,n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:clspv,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'1',debugCalls:'1',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:openclc,libs:!(),options:'-spv-version%3D1.3',overrides:!(),selection:(endColumn:55,endLineNumber:9,positionColumn:55,positionLineNumber:9,selectionStartColumn:55,selectionStartLineNumber:9,startColumn:55,startLineNumber:9),source:1),l:'5',n:'0',o:'+clspv+(trunk)+(Editor+%231)',t:'0')),k:46.74292658740967,l:'4',m:51.84432151078403,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+gcc+12.2',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+clspv+(trunk)+(Compiler+%231)',t:'0')),header:(),l:'4',m:48.15567848921597,n:'0',o:'',s:0,t:'0')),k:46.74292658740967,l:'3',n:'0',o:'',t:'0')),l:'2',m:100,n:'0',o:'',t:'0')),version:4)

**Comment by alan-baker** [comment]
It's possible your validation layers need newer spir-v headers. The reflection information changed some parsing at one point. See if updating them works out. Alternatively, see if top-of-tree SPIRV-Tools validates the shader successfully.

**Comment by rjodinchr** [comment]
I confirm that compiling this kernel with a top-of-tree clspv and `-spv-version=1.3` does not generate any error with the top-of-tree spirv validator.
