### ISSUE TITLE
Clspv crashes compiling code writing to structs with varying size fields.

### ISSUE THREAD

**Issue by BukeBeyond** [google/clspv#1166]
```
struct S { long i1; int i2; int i3; }; // Fail: i64i32*** stack smashing detected ***
// struct S { int i1; long i2; int i3; }; // OK: First field has the minimum size of all fields
// struct S { int i1; char i2; char i3; }; // Fail
// struct S { char Fix; int i1; char i2; char i3; }; // OK: byte size first field fixes all

kernel void Kernel(global struct S* s)
{
    s->i1 = 0;
    s->i2 = 0;
    s->i3 = 0;
}
```
[godbolt.org/z/533he8K96](https://godbolt.org/z/533he8K96)

**Comment by BukeBeyond** [comment]
I should add, Clang 17 pre-compiles these fine, as in https://github.com/google/clspv/issues/1142

The bug is in Clspv Vulkan conversion even when given the pre-compiled ll file.

**Comment by rjodinchr** [comment]
Thank you for the bug report.
The pull request mentioned above should fix the issue.

**Comment by BukeBeyond** [comment]
With previous GPU technologies, direct access to complex structures in memory never worked right.  So we had to implement intricate serialization to replicate objects.

But here it is, you proved this can work, after fixing this bug!

So good to see Clspv back on track, leading the pack.

Thank Mr. Jodin and Mr. Baker!
