### ISSUE TITLE
Clspv crashes on IR input accessing array of structs with different field sizes

### ISSUE THREAD

**Issue by BukeBeyond** [google/clspv#1188]
These are compiled externally with Clang 18, some crash Clspv, some succeed.
See the varying IR inputs at the godbolt.com links.

```
struct E
{
  char i; // Fails:  https://godbolt.org/z/1h8dfE1Gs
  // short i; // Fails:  https://godbolt.org/z/3v6q86bqK
  // int i; // OK:  https://godbolt.org/z/9K1a98MhK
  // long i; // OK:  https://godbolt.org/z/7jG9PaeGY
};

struct S { struct E e[200]; };

kernel void Kernel(global struct S* s)
{
  for (int i = 0; i < 200; ++i)
  {
    struct E e = s->e[i];
    e.i = 1;
    s->e[i] = e;
  }
}
```

**Comment by rjodinchr** [comment]
AFAIK clspv does not support vectors of pointers as shown in the 2 IR failing.
2 possibilities:
- add support in clspv, which is quite some work
- change your frontend to avoid generating those.

Please avoid filing bugs with a working code (the CL code above), where we have to go through links to find code failing.

Also note that using another frontend that the one used by clspv is dangerous and this is a typical case where you will need to find a solution by yourself for the time being.

**Comment by BukeBeyond** [comment]
The front end is Clang 18, the same one you will be calling internally when you sync with LLVM.  It is probably a matter of flags to disable the vectorized pointers.  If there are other changes, Clspv will have to handle them at some point.

Let me reiterate that compiling externally with Clang 17-18 has been significantly more stable than Clspv trying to call Clang itself with its own settings.  This was a rare exception.  If we were not doing such a "dangerous thing", we would be reporting 5 to 10 times more bugs in Clspv.

I understand that you may be getting exhausted, but you could be as thankful for our efforts as we have been for yours.

**Comment by rjodinchr** [comment]
It feels like you are missing something here.
Compiling like you do with clang externally and then using the generated IR could be exactly the same as what is done in clspv **IF** we had the same compile options.

You can have a look at the compile options used for clang internally in `Compiler.cpp->SetCompilerInstanceOptions`.
You can try to change things there and you should be able to get the same things as with clang externally.

Then the hard part would be to merge those changes as it would need not to regress anything [CTS](https://github.com/KhronosGroup/OpenCL-CTS) wise.

I hope this is clearer for you.
