### ISSUE TITLE
__global variables must be decorated Coherent in the general case 

### ISSUE THREAD

**Issue by dneto0** [google/clspv#126]
If two different invocations use non-atomic accesses on the same locations in a storage buffer, and at least one access is a write, then the storage buffer must be decorated Coherent.

**Comment by sheredom** [comment]
How are you going to detect the same locations were used in the presence of dynamic indexing? Or are you just going to default to Coherent?

Also, it might be worth optimizing for the case where you've only got writes to a storage buffer, as I don't think you need Coherent there?

**Comment by dneto0** [comment]
>How are you going to detect the same locations were used in the presence of dynamic indexing? Or are you just going to default to Coherent?

Default to Coherent.

I was thinking that if the programmer knew for sure, then a compiler option could be added to say -non-coherent-global
That's short of adding a noncoherent qualifier....   No way I want to fork Clang for that. :-)

> Also, it might be worth optimizing for the case where you've only got writes to a storage buffer, as I don't think you need Coherent there?

Right.  Also for only-reads case.

**Comment by alan-baker** [comment]
In the same vein, clspv currently makes the shader assumption of no-aliasing when generating shaders. This is a good default, but 1) it should be documented and 2) there should be a to generate Aliased decorations.

**Comment by alan-baker** [comment]
Plan:
1. Allocate descriptor will look if any global barrier is used in the call tree of a kernel
2. Any __global in such a kernel that is both read and written too should be marked as coherent.
 * coherency will be a new discriminant and end up in the resource variable operands
3. During SPIR-V generation when generating function parameters, need to trace and see if any resource is marked as coherent and also mark that parameter.

**Comment by dneto0** [comment]
Fully fixed by #272 ?
