### ISSUE TITLE
Improve error messages.  Currently you just get an internal error (usually UNREACHABLE).

### ISSUE THREAD

**Issue by dneto0** [google/clspv#13]
This is somewhat by design, since we haven't touched the Clang front-end.

**Comment by dneto0** [comment]
Improving error messages will save developers and Clspv maintainers time.  For example, it should take far less time to get to root cause of issues such as https://github.com/google/clspv/issues/11

**Comment by dneto0** [comment]
It seems there's some attempt to have friendly errors via a plugin ASTFrontendAction , but it doesn't seem effective.
https://github.com/google/clspv/blob/master/tools/driver/main.cpp#L126

**Comment by dneto0** [comment]
Well, the checker does work.  But the clspv build process eliminates all the declarations of vectors longer than 4 elements.  So something like `float8 x() { return (float8)(1.0); } ` will think float8 is an undefined type.
Then as per tradition, 'int' is substitued for the return type, and the extra semantic checks on vector type just pass.
So that's why the action seems somewhat ineffective.

**Comment by sheredom** [comment]
Yeah we ended up removing the 8 and 16 wide vector elements because the clang frontend took too long compiling with all the extra function declarations. The ability to use the plugin to clang to do other frontend warnings for the tool seemed useful so I left it in.

**Comment by dneto0** [comment]
Absolutely.  I now have a patch that puts those long decls back in, but just the extended vector typedefs.  And a small tweak to the plugin will get us emitting errors again.

**Comment by dneto0** [comment]
See https://github.com/google/clspv/pull/16 
Now we will error out in a more friendly way when unsupported vector types are used inside function bodies.
