### ISSUE TITLE
Loads and Stores from offset addresses are fragmented

### ISSUE THREAD

**Issue by BukeBeyond** [google/clspv#1322]
Fragmentation happens with every type, but i64 is the simplest example:
https://godbolt.org/z/15rcYscao

Related to https://github.com/google/clspv/issues/1318

**Comment by BukeBeyond** [comment]
Trying right away!

**Comment by rjodinchr** [comment]
Note that it will not remove the fragmentation but only reduce it.
This is because this test is performing "unaligned" accesses.

**Comment by BukeBeyond** [comment]
It is working here, quite well actually!

About the alignment:
```
  %5 = load i64, ptr addrspace(1) %4, align 8
  %6 = getelementptr inbounds i8, ptr addrspace(1) %3, i64 44
  store i64 %5, ptr addrspace(1) %6, align 8
```
I see alignment, is there something else missing?

I compiled several variations of the above trigger after this fix.  I also examined 35 programs, some above 100Kb in binary Spriv size, looking for fragmented (OpLoad %uchar 's and OpCompositeConstruct's).  32 are now completely fragment free.  There was a specific case before this fix, 19kb in binary Spirv size, now it is under 14kb!

So something is working very well!  Nothing is ever perfect, but soon we may get close enough. :-)

Thank you again Romaric.

**Comment by rjodinchr** [comment]
What I meant by alignement, is that in Vulkan SPIR-V, if you have a SPIR-V variable defined as a `i64` and you want to load a `i64` from it at the offset 36, that makes an unaligned read that is not legal.
That's why is the end when you compiled your example with this fix, you can still see 2 `i32` loads to perform the `i64` load.

**Comment by BukeBeyond** [comment]
I see.  I will look for any missing alignment as a possible trigger in the remaining cases. 

But in most cases, these loads and stores are in fact, just flattened structures in memory, so Clang preserves their alignment.  In our case, these structures get quite complex, which really challenges the old GEP code in Clspv, so we have been striving to flatten and reduce them to simple direct addresses.

I think getting your internal compilation to flatten these structure, will achieve the same stability we have been experiencing since the i8 GEP evolution.  Optimisation passes, and some exclusive to Clang, have been able to flatten structures more completely after detecting them with the new and simplified byte offsets.
