### ISSUE TITLE
Error in LinkBuiltinLibrary

### ISSUE THREAD

**Issue by bmanga** [google/clspv#1343]
The latest clspv results in:
```llvm
target datalayout = "e-p:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-G1"; Function Attrs: convergent inlinehint mustprogress norecurse nounwind
define linkonce_odr spir_func float @_ZN4core6frexpfEfPi(float %value, ptr %exp)
; Function Attrs: convergent inlinehint mustprogress norecurse nounwind
define linkonce_odr spir_func float @_ZN4core6frexpfEfPU3AS1i(float %value, ptr addrspace(1) %exp)
; Function Attrs: convergent inlinehint mustprogress norecurse nounwind
define linkonce_odr spir_func float @_ZN4core6frexpfEfPU3AS3i(float %value, ptr addrspace(3) %exp)
@clspv.builtins.used = appending global [3 x ptr] [ptr @_ZN4core6frexpfEfPi, ptr @_ZN4core6frexpfEfPU3AS1i, ptr @_ZN4core6frexpfEfPU3AS3i], section "llvm.metadata"
internal_additional_library:: error: expected '{' in function body
define linkonce_odr spir_func float @_ZN4core6frexpfEfPU3AS1i(float %value, ptr addrspace(1) %exp)
```
I can't share the module I'm trying to link, but the issue might have to do with `frexp`:
https://github.com/google/clspv/blob/118d65ebfd6a747dc588a871535ce8c0da04a88f/lib/Compiler.cpp#L1037

**Comment by bmanga** [comment]
Functions that contain those names (frexp, modf, etc...) in their name and have a correct signature seem to trigger it. For example:
```cpp
void as_long_as_contains_frexp_in_name(float, int *) {}
```
godbolt: https://gcc.godbolt.org/z/aT6a6ExWo

**Comment by rjodinchr** [comment]
I guess [Builtins::BuiltinWithGenericPointer](https://github.com/google/clspv/blob/118d65ebfd6a747dc588a871535ce8c0da04a88f/lib/Builtins.cpp#L779) needs to be improved. Can you submit a PR that fix your usecase?

**Comment by rjodinchr** [comment]
Or maybe you could add functions declaration in `GetEquivalentBuiltinsWithoutGenericPointer` only if they are part of `library` (from `LinkBuiltinLibrary`). Using something like `library->getFunction(<name>)`?

**Comment by bmanga** [comment]
Thanks for the suggestions... I'll have a look!
I have a question though: Why does [Builtins::BuiltinWithGenericPointer](https://github.com/google/clspv/blob/118d65ebfd6a747dc588a871535ce8c0da04a88f/lib/Builtins.cpp#L779) check for names containing the function name and not for an exact match?
