### ISSUE TITLE
-mfmt=c is not a valid option

### ISSUE THREAD

**Issue by robquill** [google/clspv#1346]
README.md says:

Emit the binary as a C initializer list, for easy embedding of a shader in
in a C or C++ program source:

    clspv -mfmt=c foo.cl -o -

Bu it should say:

    clspv --output-format=c foo.cl -o -

It also isn't documented in --help. I had to find test/mfmt_c.cl to find out what the right option was.

**Comment by alan-baker** [comment]
Thanks for the report. Looks like we forgot the documentation updates when we unified some options.

**Comment by rjodinchr** [comment]
It feels like the documentation is there to me:
```
$ clspv --help | grep -A 4 "output-format"
  --output-format=<value>                                    - Select output format (ll|bc|spv|c)
    =spv                                                     -   Vulkan SPIR-V
    =ll                                                      -   Readable LLVM IR (Stop compilation before clspv specific passes)
    =bc                                                      -   Binary LLVM IR (Stop compilation before clspv specific passes)
    =c                                                       -   C initializer list (of Vulkan SPIR-V)
```

I'll update the README

**Comment by robquill** [comment]
Thanks for fixing this.
