### ISSUE TITLE
printf does not handle "\0"

### ISSUE THREAD

**Issue by rjodinchr** [google/clspv#1371]
https://compiler-explorer.com/z/Thv1cjGr9

The following kernel does not generate any nodes for `"\0"`:
```
__kernel void test_kernel()
{
    printf("%s", "\0");
    printf("%s", "test");
}
```

**Comment by dneto0** [comment]
This causes the test_printf conformance test to fail because has a case like `"foo\0foo"`

https://github.com/KhronosGroup/OpenCL-CTS/blob/070052c890c83053c5243e32b5bec8b84b04344d/test_conformance/printf/util_printf.cpp#L749

**Comment by Rekt3421** [comment]
taking a look at this now.
