### ISSUE TITLE
update kokoro configs to use python 3.8 or later

### ISSUE THREAD

**Issue by dneto0** [google/clspv#1377]
The bots fail now, since LLVM requires python 3.8 or later.  e.g. https://github.com/google/clspv/pull/1376 

This needs to wait until we've updated our Kokoro images to *have* python 3.8 or later.

**Comment by dneto0** [comment]
I've failed Google internal bug https://b.corp.google.com/issues/350048185 for the image upgrade

**Comment by dneto0** [comment]
still need to update the Windows image

**Comment by rjodinchr** [comment]
fixed by https://github.com/google/clspv/pull/1409
