### ISSUE TITLE
Add OpLine Information for Atomic Instructions

### ISSUE THREAD

**Issue by CapZTr** [google/clspv#1400]
Hi! `clspv` does not generate OpLine information for any atomic instructions so far. Does someone have a idea of how it can be fixed?

**Comment by rjodinchr** [comment]
I think `clspv` is not passing the debug information somewhere in the flow.

Taking an example and compiling it with `--print-before-all` should help identify the pass.

@CapZTr Do you want to have a look yourself? Otherwise @Rekt3421 can find sometime to look at it I think.

**Comment by CapZTr** [comment]
Hey @rjodinchr , thanks for the quick reply! This issue is fixed and I created the PR #1403 for it:-)
