### ISSUE TITLE
WorkGroupSize declared but not referenced

### ISSUE THREAD

**Issue by pdsharma0** [google/clspv#154]
My CL kernel doesn't have any reference to **get_work_dim()**:
```
// Copy src buffer data into dst
__kernel void CopyBuffer(__global unsigned* src, __global unsigned* dst) {
	unsigned threadId = get_global_id(0);
	dst[threadId] = src[threadId];
}
```
But the SPIR-V still allocates a vec3 pointer which isn't referenced in later sections. This probably wastes register space. Relevant section of disassembly:

```
	OpDecorate %17 BuiltIn WorkgroupSize
%1 = 	OpTypeInt 32 0
%8 = 	OpTypeVector %1 3
%11 = 	OpTypePointer Private %8
%14 = 	OpSpecConstant %1 1
%15 = 	OpSpecConstant %1 1
%16 = 	OpSpecConstant %1 1
%17 = 	OpSpecConstantComposite %8 %14 %15 %16
%18 = 	OpVariable %11 Private %17
```

**Comment by ericberdahl** [comment]
I don't believe that is an error.

Your kernel also does not specify a workgroup size (via #pragma). Therefore, this kernel expects software to set the workgroup size at submit time. In OpenCL, this is done through an OpenCL host API. However, SPIR-V graphics dialect requires workgroup sizes to be specified in the SPIR-V module.

Your host software can specify the workgroup size for the kernel by setting the spec-constants when creating the compute pipeline for this kernel.

**Comment by pdsharma0** [comment]
I did't mean to say the SPIRV is incorrect by any stretch but was just pointing out a minor optimization. I didn't like this variable to just sit there and not really being useful:
```
%18 = 	OpVariable %11 Private %17
```
But if the graphics spec requires it then who am I to complain. I guess it always needs it for the GLSL built in constant : gl_WorkGroupSize.

Adding reqd_work_group_size(1, 1, 1) does away with the above OpVariable declaration so it has one less pointer in register space. I guess I'll stick with kernel based work-group sizes which also allows IHVs to optimize shader resources better.  Thanks for the explanation!
