### ISSUE TITLE
Presence of double-precision constants causes internal error

### ISSUE THREAD

**Issue by jaebaek** [google/clspv#157]
The following code has `UNREACHABLE executed at lib/SPIRVProducerPass.cpp:2179!` error.

```C
const sampler_t sampler =
CLK_NORMALIZED_COORDS_TRUE | CLK_ADDRESS_REPEAT | CLK_FILTER_NEAREST;

kernel void foo(global float* out,
                global float* in,
                __read_only image2d_t inImage) {
  uint i = get_global_id(0);
  float sum = 0.0f;
  for (int j = 0; j < 4;++j)
    sum += read_imagef(inImage, sampler, (float2)(0.05 * (float)i, 0.05 * (float)i))[j];
  out[i] = in[i] + 100.0f * sum;
}
```

I think it is caused by `0.05 * (float)i` in the third argument of `read_imagef()`.
If I changed it as `0.05f * (float)i`, the error disappeared.

Is it an intended behavior e.g., no implicit converting from double to float ?

**Comment by dneto0** [comment]
The floating point literals are of type "double" in C.    Use the flag -cl-single-precision-constant to force the compiler to treat them as "float".   Either that or append 'f' to the number, e.g. 0.05f.

This is a known issue.   Normally you don't want to imply 64-bit floats just for the literals when the rest of the program is using only 32-bit floats.
