### ISSUE TITLE
read_imagef on 3d images with integer coordinates is not supported

### ISSUE THREAD

**Issue by dneto0** [google/clspv#158]
For 2d images, ReplaceOpenCLBuiltins knows how to translate a read_imagef on integer coordinates into a read_imagef with float coordinates.  But it doesn't do the same for 3d images.  This is an asymmetry we should fix.

Example:
```
kernel void foo(global float4* A, image3d_t im, sampler_t s, int4 coord) {
  *A = read_imagef(im, s, coord);
}
```
Yields:

`Can't translate function call.  Missing builtin? _Z11read_imagef14ocl_image3d_ro11ocl_samplerDv4_i in:   %call = tail call spir_func <4 x float> @_Z11read_imagef14ocl_image3d_ro11ocl_samplerDv4_i(%opencl.image3d_ro_t addrspace(1)* %im, %opencl.sampler_t addrspace(2)* %s, <4 x i32> %coord) #2`

However, it compiles fine if we either use a 2d image or float4 coordinates.

**Comment by alan-baker** [comment]
Fixed by #457
