### ISSUE TITLE
map pointer-to-constant kernel arguments to uniform buffers if alignment rules satisfied

### ISSUE THREAD

**Issue by dneto0** [google/clspv#168]
Today they are mapped to storage buffers.  Uniform buffers can be faster.

This change would need an enhancement to verify that the pointee type satisfies the extra alignment requirements for uniform buffers.  See Vulkan section 14.5.4 Offset and Stride Assignment for the rules. https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html#interfaces-resources-layout 
The key difference is that uniform buffers have an additional constraint that the base alignment of a struct or an array must be a multiple of 16.

Note that OpenCL C supports a standard alignment attribute for types.  See OpenCL 1.2 section 6.11.1 "Specifying attributes of types".

Example:

     struct S { short f[3]; } __attribute__ ((aligned (8)));
     typedef int more_aligned_int __attribute__ ((aligned (8)));

**Comment by dneto0** [comment]
Clarification. The previous example was from the OpenCL spec, showing the syntax to specify alignment.

Here is an example which would satisfy the uniform buffer alignment constraints:

```
typedef struct {
  int ba;
  int bb;
} Inner;

typedef struct {
  int a;
  Inner b __attribute__((aligned(16)));  // Because this is a struct
  int c[2] __attribute__((aligned(16)));  // because this is an array.
  int d;
} S;

kernel void foo(global int *A, constant S *C) { *A = C->b.ba; }
```

This is how the Clang front-end translates the types:
```
%struct.S = type { i32, [12 x i8], %struct.Inner, [8 x i8], [2 x i32], i32, [4 x i8] }
%struct.Inner = type { i32, i32 }
```
The [12 x i8] and [8 x i8] are dummy entries struct members that Clang inserts solely to enforce alignment constraints.    

So if the programmer annotates source as above, then clspv would (1) deduce that it should ignore the char array dummy entries, and (2) see that uniform buffer alignment constraints are satisfied.

**Comment by dneto0** [comment]
Ah, and the [4xi8] at the end ensures the last 4 bytes are filled out as well.

**Comment by alan-baker** [comment]
Dup of #208. Closing this since #208 has mentions in commits.
