### ISSUE TITLE
take advantage of SPV_KHR_8bit_storage

### ISSUE THREAD

**Issue by dneto0** [google/clspv#169]
The 8bit storage extension allows reading and writing 8bit values, provided those values are immediately converted to (or from) a wider type. It does not enable 8bit arithmetic for example.

http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_8bit_storage.html

**Comment by dneto0** [comment]
This should be similar to -f16bit_storage

**Comment by alan-baker** [comment]
Duplicate of #280
