### ISSUE TITLE
About int16 requeriments..

### ISSUE THREAD

**Issue by oscarbg** [google/clspv#18]
Hi,

seeing "OpenCL C 1.2 Language on Vulkan" document I see:
"if the short/ushort types are used in the OpenCL C: **shaderInt16** is required"

that's sad as seeing http://vulkan.gpuinfo.org reports shaderInt16 isn't supported by Nvidia GPU drivers and also not by AMD GPU Windows and RADV Linux drivers and not also by Intel Mesa drivers..
In fact only GPU OS system that has it is Intel Windows Vulkan drivers..

but I also see VK_KHR_16bit_storage new ext that allows " use of 16-bit types in shader input and output interfaces"
 so seems this is also required if using int16 in OpenCL kernel arguments..

so questions are:
*VK_KHR_16bit_storage is also required in addition to shaderInt16 for kernels with int16 arguments?

*can shaderInt16 restriction be avoided by requiring only VK_KHR_16bit_storage for kernels with int16 
variables/arguments by "treating it" internally as int32 for operations using it but storing as 16bits using VK_KHR_16bit_storage?

thanks..

**Comment by sheredom** [comment]
Hey @oscarbg:

> VK_KHR_16bit_storage is also required in addition to shaderInt16 for kernels with int16 arguments?

We don't need `VK_KHR_16bit_storage` as long as `shaderInt16` is supported.

> can shaderInt16 restriction be avoided by requiring only VK_KHR_16bit_storage for kernels with int16 variables/arguments by "treating it" internally as int32 for operations using it but storing as 16bits using VK_KHR_16bit_storage?

In theory this could work - but it fails on something important that we see in a lot of OpenCL C kernels. A ton of OpenCL C kernels use pointer bitcasts to reinterpret a buffer as another type - something which **fundamentally Vulkan SPIR-V does not support**. To work around this a huge amount of the effort in this porting effort was in transforming any pointer bitcasts we see in the code into a load/store and a _value_ bitcast instead.

If we could not use the `shaderInt16` capability we would be unable to transform code like:

```
global int* a;
short b = ((global short*)a)[10];
```

So yes - the compiler could be made to work without the `shaderInt16` capability, but we'd be unable to support some of the usecases we have for this code.

**Comment by alan-baker** [comment]
Closing in favour of the https://github.com/google/clspv/milestone/1 milestone.
