### ISSUE TITLE
constant generation: generates an OpConstant for the alignment value on OpCopyMemory when it doesn't have to

### ISSUE THREAD

**Issue by dneto0** [google/clspv#184]
The internal intrinsic spirv.copy_memory intrinsic will generate an Aligned literal operand with the alignment value taken from one of its arguments.

E.g. 
```
  call void @spirv.copy_memory(%struct.a addrspace(1)* %struct_out, %struct.a* nonnull %local_a, i32 4, i32 0) #1
```
Will result in `OpCopyMemory %57 %56 Aligned 4 ` but also `  %uint_4 = OpConstant %uint 4    `, where `%uint_4` could be dead.

The compiler should be able to sweep away dead constants like this, or avoid generating them in the first place.

**Comment by rjodinchr** [comment]
copy_memory does not exist anymore. It has been removed by #1119 .
