### ISSUE TITLE
support out-of-tree SPIRV-Tools and SPIRV-Headers where the spirv-dis target doesn't exist yet

### ISSUE THREAD

**Issue by dneto0** [google/clspv#203]
For example, 

With this kind of command line:
```
cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DSPIRV_TOOLS_SOURCE_DIR=/foosrc/third_party/SPIRV-Tools -DSPIRV_HEADERS_SOURCE_DIR=/foosrc/third_party/SPIRV-Headers ../clspv
```

Currently, I get an error like this:

```
CMake Error at test/CMakeLists.txt:17 (add_custom_target):
  Error evaluating generator expression:

    $<TARGET_FILE_DIR:spirv-dis>

  No target "spirv-dis"
```

In this case we then add the SPIRV-Tools project from that other location?
See comment on #202

**Comment by dneto0** [comment]
I'm interested in @kpet's input.

**Comment by kpet** [comment]
Yes, I wasn't trying to solve that case with #202, only the case where clspv is embedded into another project that provides the targets. The `check-spirv` target also depends on several of the SPIRV tools.

>In this case we then add the SPIRV-Tools project from that other location?

Yes, I think that works. The first solution that comes to mind is to check whether one of (assuming they all exist when a single one does) the tools targets exist and add the project if it doesn't. I think this would cater for all cases. I can have a go at implementing that if you think that's a suitable solution.

Alternatively we could make the dependencies on the various tools conditional to the user passing a path to the built tools (with the default constructed from one of the targets as in #202). This means one doesn't potentially build SPIRV-Tools twice (assuming the folder passed is also used to work on SPIRV-Tools standalone) but it's quite a bit clunkier if one changes SPIRV-Tools as part of working on clspv.
