### ISSUE TITLE
Build errors with MSVC

### ISSUE THREAD

**Issue by rszymanski** [google/clspv#212]
C:\clspv\lib\SPIRVProducerPass.cpp(1009): error C2220: warning treated as error - no 'object' file generated
C:\clspv\lib\SPIRVProducerPass.cpp(1009): warning C4100: 'DL': unreferenced formal parameter
C:\clspv\lib\SPIRVProducerPass.cpp(1010): warning C4189: 'SPIRVInstList': local variable is initialized but not referenced
C:\clspv\lib\SPIRVProducerPass.cpp(1011): warning C4189: 'VMap': local variable is initialized but not referenced
C:\clspv\lib\SPIRVProducerPass.cpp(1266): warning C4456: declaration of 'Call' hides previous local declaration
C:\clspv\lib\SPIRVProducerPass.cpp(1240): note: see declaration of 'Call'
C:\clspv\lib\SPIRVProducerPass.cpp(1419): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
C:\clspv\lib\SPIRVProducerPass.cpp(1424): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
C:\clspv\lib\SPIRVProducerPass.cpp(2427): warning C4189: 'VMap': local variable is initialized but not referenced
C:\clspv\lib\SPIRVProducerPass.cpp(2541): warning C4100: 'M': unreferenced formal parameter
C:\clspv\lib\SPIRVProducerPass.cpp(3032): warning C4189: 'DL': local variable is initialized but not referenced
C:\clspv\lib\SPIRVProducerPass.cpp(4294): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
C:\clspv\lib\SPIRVProducerPass.cpp(4312): warning C4244: 'argument': conversion from 'const uint64_t' to 'const KeyT', possible loss of data

**Comment by dneto0** [comment]
Presuming this is fixed now. #213 has been merged.
