### ISSUE TITLE
Differences between OpenCL and Vulkan image handling

### ISSUE THREAD

**Issue by alan-baker** [google/clspv#219]
OpenCL allows querying the image size of an image that will be sampled, but Vulkan does not. Specifically, Vulkan requires knowing whether the image will be used with a sampler or not at compile time (sampled operand must be 1 or 2).

Currently clspv maps (2D images) as follows:
* `opencl.image_2d_ro_t` -> `OpTypeImage float 2D 0 0 0 1`
* `opencl.image_2d_wo_t` -> `OpTypeImage float 2D 0 0 0 2`

If the program uses `get_image_height` or `get_image_width` on a read only image then that image cannot be used with a sampler. clspv would have to generate the same image OpTypeImage as for the write only case; however, that would be incompatible if the sampled variant of `read_image` were also used.

Maybe this could solved with an aliased binding, but that would generate headaches throughout the flow.

**Comment by alan-baker** [comment]
Worth noting that OpenCL would generally want to generate image with a sampling of 0.

**Comment by alan-baker** [comment]
I don't think aliased bindings will work. The Vulkan API requires that the VK_DESCRIPTOR_TYPE matches the binding if it is used by the shader. The descriptor type cannot be both VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE (or VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER) **and** VK_DESCRIPTOR_TYPE_STORAGE_IMAGE so the two handles could not be used in the same shader.

**Comment by kpet** [comment]
If the only problem here is to support `get_image_height` or `get_image_width` then a possible solution could be to pass the information directly via the runtime/application (via push constants or uniforms).

**Comment by alan-baker** [comment]
Yes, but that sounds like entries in the descriptor map that don't correspond directly existing kernel args (though are strongly tied to an existing arg). That's not necessarily a bad thing, but certainly is more work to support.

**Comment by alan-baker** [comment]
OpImageQuerySize for unsampled images.
OpImageQuerySizeLod for sampled images.

**Comment by alan-baker** [comment]
I should note this is easier now that image specialization is done.
