### ISSUE TITLE
vloadn/vstoren produces incorrect code when addresses aren't aligned to the vector type

### ISSUE THREAD

**Issue by kpet** [google/clspv#232]
The approach taken by `replace{Vload,Vstore}` in the `ReplaceOpenCLBuiltinPass` pass is to cast the pointer to a pointer to the vector type and use a load/store instruction. This interacts badly with `SimplifyPointerBitcastPass::runOnBitcastFromGEP` resulting in the address being rounded down and aligned to the vector size.

**Comment by s-perron** [comment]
+1
