### ISSUE TITLE
clspv windows build not working with visual studio 2017 (19.15.26732.1)

### ISSUE THREAD

**Issue by pscoe2** [google/clspv#238]
clspv build is broken on the latest VS. The issue is due to warnings 4424 and 4071 being issued in SPIRVProducerPass.cpp. Adding skip for them in CMakeLists.txt fixes the build

Build error log:
https://pastebin.com/7MpHjYgR

**Comment by pscoe2** [comment]
The clspv.exe generated after adding ignore to those warnings seems broken. Thus the above solution might not be the correct one

**Comment by alan-baker** [comment]
Compile is fine, but clspv still seems to be failing on some kernels that work on Linux.
