### ISSUE TITLE
Support cl_khr_fp16 via new VK_KHR_shader_float16_int8 float16 capability?

### ISSUE THREAD

**Issue by oscarbg** [google/clspv#252]
would be nice to have..

**Comment by alan-baker** [comment]
We agree, but it will not implemented in the short term.

**Comment by dneto0** [comment]
I'm hearing requests for this from a few directions.  :-)

**Comment by alan-baker** [comment]
I have created two milestone for char and half support. Closing this in favour of those breakdowns.
