### ISSUE TITLE
Remove generation of SPIR-V disassembly

### ISSUE THREAD

**Issue by alan-baker** [google/clspv#265]
Too much duplicated code and testing requirements. clspv should only output SPIR-V binary. Use SPIRV-Tools to disassemble the binary.

Start by deprecating the option in clspv.

**Comment by kpet** [comment]
Given the experimental nature of clspv and unless you know of someone relying on it (they shouldn't :)), I'm tempted to suggest to just remove support.

**Comment by kpet** [comment]
FWIW, no longer checking the output of `-S` roughly doubles the speed of the test suite. I can submit the change if people think it's the right time to do it.

**Comment by alan-baker** [comment]
Yes please if you have that change. In fact, you could also remove -S command line option and leave the code in SPIRVProducerPass to be stripped a bit later.

**Comment by notzed** [comment]
The main README.md confusingly still mentions the -S flag.

**Comment by kpet** [comment]
@notzed Thanks for reporting this!
