### ISSUE TITLE
Clean up the lit tests: match patterns more narrowly

### ISSUE THREAD

**Issue by alan-baker** [google/clspv#267]
The vast majority of lit tests for clspv just check the exact SPIR-V that is produced by the compiler. This is not a good testing strategy and results in large amounts of wasted developer time updating tests for unrelated changes.

Tests should be updated to have targeted CHECK statements that look for specific features.

This is a large amount of work.

**Comment by dneto0** [comment]
I agree.  The current style was an expedient choice during early iterations of the project.

I'd like us to use googletest and use the google/effcee library to do FileCheck-like testing.  This has worked very well for DirectXShaderCompiler's SPIR-V backend.

**Comment by dneto0** [comment]
Hey @alan-baker  I think you might be finished doing this?
