### ISSUE TITLE
Signed Integer Types

### ISSUE THREAD

**Issue by jgavris** [google/clspv#273]
In the OpenCL-on-Vulkan [spec](https://github.com/google/clspv/blob/master/docs/OpenCLCOnVulkan.md#signed-integer-types):

>Signed integer types are mapped down onto their unsigned equivalents in SPIR-V
as produced from OpenCL C.

I'm just wondering why this is? 

I'm relatively new to SPIR-V, but my understanding of the spec is that `OpTypeInt` has signedness. This seems like a particularly dangerous conversion if you aren't paying attention to the spec and kernels, and no warnings are emitted by `clspv`.

**Comment by alan-baker** [comment]
LLVM does not track the signedness of integer types. Where the interpretation of the sign is important, both specs encode that information in the opcode of the instructions (e.g. signed integer division).

**Comment by jgavris** [comment]
Ah, indeed. I ran a couple test cases to convince myself. Thanks!
