### ISSUE TITLE
Support integer-based image reads and writes

### ISSUE THREAD

**Issue by alan-baker** [google/clspv#286]
Support the following builtins:
* read_imagei
* read_imageui
* write_imagei
* write_imageui

This could be broken up to support 2D images first and 3D images later.

**Comment by kpet** [comment]
I've done some work there but there are a number of cleanup changes in the `SPIRVProducerPass` that I'd like to do before completing this.

**Comment by alan-baker** [comment]
There will be difficulties with this if the image format is not the same width as the read/write. There is a SPIR-V internal issue about it.

**Comment by kpet** [comment]
Good to know, thanks. Do you have a link?

**Comment by alan-baker** [comment]
Khronos SPIR-V internal issue #332
