### ISSUE TITLE
Compile error when using convert_<type>

### ISSUE THREAD

**Issue by Ardy123** [google/clspv#291]
When using convert_<type> (such as convert_char4), clspv emits the following errors..

Can't translate function call.  Missing builtin? _Z14convert_uchar4Dv4_j in:   %call41 = tail call spir_func <4 x i8> @_Z14convert_uchar4Dv4_j(<4 x i32> %call40) #3

**Comment by kpet** [comment]
I've been working on a patch for the basic `convert_` built-in functions that would cover this one. This requires a minimal demangler/type query utility that I've written as part of implementing `mul_hi`/`mad_hi`.
