### ISSUE TITLE
Should Output be reversable with SPIRV-Cross?

### ISSUE THREAD

**Issue by Ardy123** [google/clspv#306]
I've noticed that sometimes output from clspv results in code that cannot be reversed with SPIRV-cross as it returns the following error (even when there are not nested loops).

`SPIRV-Cross threw an exception: Over 3 compilation loops detected. Must be a bug!`

**Comment by dneto0** [comment]
Assuming the output from Clspv is correct, that would be an issue for SPIRV-Cross.

I'd suggest running spirv-val --target-env vulkan1.0 on the output of Clspv.  If that says it's ok, then the module is probably valid.

This is not an actionable issue.  Closing.
