### ISSUE TITLE
Make sure SPIR-V intrinsics have got a unique name

### ISSUE THREAD

**Issue by kpet** [google/clspv#308]
Functions and calls are used in a number of places to encode specific SPIR-V instructions. In several cases the same function name is used with different type signatures, making it impossible to use both in the same module. All uses of functions to encode SPIR-V instructions should be reviewed to ensure they don't suffer from this issue. Each time a single test that uses all possible overloads should be added.

**Comment by rjodinchr** [comment]
I think this is now fixed. Closing the issue. Feel free to reopen if I am wrong here.
