### ISSUE TITLE
Issues with loading signed char data and converting it to int

### ISSUE THREAD

**Issue by Ardy123** [google/clspv#310]
When loading say -109 as signed char data from a buffer, then converting to int, it gets treated as 147 instead of -109... 

for example..
If buffer is { 112, -109, -19, 100 };

and the opencl code is..
int4 val = convert_int4(testData[i]);

then val.y  = 147 and not -109 (Both have the same hex value... 0x93, 0x93)

**Comment by alan-baker** [comment]
Given:
```
kernel void foo(global int* out, global char* in) {
  *out = convert_int(*in);
}
```

We generate:
```
%27 = OpLoad %uchar %26
%28 = OpSConvert %uint %27
```
This looks correct to me. OpSConvert performs a sign extend or truncate. I would suggest this is similar to #302.

**Comment by Ardy123** [comment]
Should the resultant code be...

%28 = OpSConvert %int %27

And not uint.. explaining the bug?

**Comment by alan-baker** [comment]
The opcode specifies that any widening is a sign extension. The sign bit of the result type should be ignored.

**Comment by dneto0** [comment]
The problem is not with Clspv. (Is this another SPIRV-Cross artifact?)
