### ISSUE TITLE
Compile issue of Master

### ISSUE THREAD

**Issue by Ardy123** [google/clspv#315]
/Users/ardy/code/clspv/lib/AllocateDescriptorsPass.cpp:724:71: error: member reference type 'llvm::Constant *' is a pointer; did you mean to use '->'?
          var_fn = cast<Function>(M.getOrInsertFunction(fn_name, fnTy).getCallee());
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
                                                                      ->
/Users/ardy/code/clspv/lib/AllocateDescriptorsPass.cpp:724:72: error: no member named 'getCallee' in 'llvm::Constant'
          var_fn = cast<Function>(M.getOrInsertFunction(fn_name, fnTy).getCallee());
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/ardy/code/clspv/lib/AllocateDescriptorsPass.cpp:871:67: error: member reference type 'llvm::Constant *' is a pointer; did you mean to use '->'?
              cast<Function>(M.getOrInsertFunction(fn_name, fn_ty).getCallee());
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
                                                                  ->
/Users/ardy/code/clspv/lib/AllocateDescriptorsPass.cpp:871:68: error: no member named 'getCallee' in 'llvm::Constant'
              cast<Function>(M.getOrInsertFunction(fn_name, fn_ty).getCallee());
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
4 errors generated.

**Comment by kpet** [comment]
My guess would be that you've updated clspv past the clang/llvm update but haven't re-run `utils/fetch_sources.py`.

**Comment by Ardy123** [comment]
I have, ran it right before... is there a way to blow out the 'built' directory for the external dependencies its building?

**Comment by dnovillo** [comment]
> My guess would be that you've updated clspv past the clang/llvm update but haven't re-run `utils/fetch_sources.py`.

Yes.  That's exactly right.  @alan-baker updated LLVM last week and these calls have changed in recent LLVM.

**Comment by Ardy123** [comment]
Nevermind.. I got it to build by deleting all the code and getting it fresh again
