### ISSUE TITLE
clspv-opt option parsing broken

### ISSUE THREAD

**Issue by kpet** [google/clspv#322]
`clspv-opt` is using substring searches (checking whether a given argument contains an option name) to determine which options to parse itself and which options it should pass to `opt`. One of the options in the search list is `debug` which means that passing a file that has `debug` in its name makes `clspv-opt` think that it's an option it should parse. It will need something more robust.

**Comment by dnovillo** [comment]
This will be fixed as a side-effect of fixing #307.  It's forced me to re-implement clspv-opt from whole cloth instead of using the plugin facilities of LLVM opt.  I'm currently working on this.

**Comment by dnovillo** [comment]
Fixed with a4c44fa
