### ISSUE TITLE
-print-{after,before}-all is broken

### ISSUE THREAD

**Issue by kpet** [google/clspv#361]
This was apparently broken by `a4c44fae` (Re-implement clspv-opt as a standalone driver).

**Comment by dnovillo** [comment]
Working on this today.

**Comment by dnovillo** [comment]
Could you be more specific about what you mean by "broken"?  Both options are working fine for me.

**Comment by kpet** [comment]
@dnovillo None of the clspv passes are showing up in the output for me.

**Comment by dnovillo** [comment]
Thanks.  I see the failure now.
