### ISSUE TITLE
Output source level debug info into spir-v output

### ISSUE THREAD

**Issue by CaffeinePwrdAl** [google/clspv#367]
Unless I missed the option, there doesn't appear to be an option to output the spir-v binary with debug source info from the original kernel - the equivalent of -g on glslangValidator.

This can be useful for tools that can do source-line debugging using the embedded debug info.

Cheers,

Alex

**Comment by rjodinchr** [comment]
This is now supported and used in [compiler-explorer](https://godbolt.org/z/e4e8Y5ss8)
