### ISSUE TITLE
Is clspv intended as a replacement for the Khronos OpenCL C compiler?

### ISSUE THREAD

**Issue by MarkIngramUK** [google/clspv#373]
Apologies if this is covered elsewhere, but I couldn't see a reference to this on the `readme.md`.

Is `clspv` intended as a replacement for the Khronos OpenCL C compiler (SPIR-V 1.1 - https://github.com/KhronosGroup/SPIR/tree/spirv-1.1)?

**Comment by alan-baker** [comment]
No, clspv converts OpenCL C kernels into Vulkan compute shaders. It does not generate OpenCL kernels.

**Comment by MarkIngramUK** [comment]
The `spirv-1.1` branch (linked above) takes an OpenCL C (or C++) kernel and also converts them into SPIR-V. I tried the Khronos project, and `clspv`, and they both work fine with the simple test cases I attempted. So I was intrigued as to why there are two similar projects, doing the same thing (though suspected the lack of activity on the Khronos project may have been a factor)..

**Comment by alan-baker** [comment]
There are two main flavours of SPIR-V: kernels and shaders. OpenCL targets the Kernel capability in SPIR-V and Vulkan targets the Shader capability. clspv specifically crosses the boundary of starting with OpenCL C and targeting the Shader capability.

**Comment by MarkIngramUK** [comment]
Thanks @alan-baker, I'm looking at this with respect to compute. What's the reason `clspv` targets the shader capability, and not the kernel capability (as OpenCL itself was kernel based)? I guess that explains why `clspv` emits `SPV_KHR_storage_buffer_storage_class` into the SPIR-V.

**Comment by alan-baker** [comment]
The goal is to run OpenCL C kernels in the Vulkan runtime (instead of writing GLSL or HLSL shaders).

**Comment by MarkIngramUK** [comment]
That’s also my goal, but I think my confusion has come from assuming Vulkan could execute the SPIR-V compute flavour too. Which I’m assuming from your comment that it can’t?
Do you create the pipelines via `vkCreateComputePipelines` still?

**Comment by alan-baker** [comment]
Compute shaders (for Vulkan) use the GLCompute execution model on an entry point, whereas OpenCL kernels use the Kernel execution model. They are both compute models.

vkCreateComputePipelines expects a GLCompute entry point.

**Comment by MarkIngramUK** [comment]
Thanks @alan-baker, that's the key piece of info that I was missing. Thanks for taking the time to respond, I really appreciate it.
