### ISSUE TITLE
crash when handling mutually recursive struct types

### ISSUE THREAD

**Issue by dneto0** [google/clspv#376]
I get a crash when trying to compile this.

```c
struct T;
typedef struct S {
  struct T* pt;  // forward-declared pointer type.
  int a;
} S;

typedef struct T { 
  S* ps;
} T;

kernel void foo(global S* s) {
  s->a = 1;
}
```
Vanilla Vulkan can't support this anyway.  Maybe it's better to error out.

**Comment by alan-baker** [comment]
This is crashing in the producer pass trying to find the right type. Basically there is no logic to generate forward pointers. I agree a frontend error might is likely better.
