### ISSUE TITLE
Ingest OpenCL-flavored SPIR-V

### ISSUE THREAD

**Issue by fodinabor** [google/clspv#435]
Would it be possible to feed clspv OpenCL-flavored SPIR-V and get Vulkan-flavored SPIR-V out of it?
If not, what would have to be done?

Using the SPIR-V Cross tools it might be possible to get valid LLVM IR, that's similar to what clspv uses somewhere internally?
Or are all the Khronos SPIR-V tools mostly Vulkan-flavor focused?

**Comment by kpet** [comment]
This is not something that clspv supports out-of-the-box but you can try to do it (this is not going to work for all SPIR-V modules) using the [SPIRV-LLVM Translator](https://github.com/KhronosGroup/SPIRV-LLVM-Translator):

```
llvm-spirv -r -o opencl-ir.bc opencl-spirv.spv
clspv -x ir -o vulkan-spirv.spv opencl-ir.bc
```

Unfortunately, the master branches of clspv and the translator aren't always compatible at any one time (and definitely not as I type this). Both clspv and the translator are used by [clvk](https://github.com/kpet/clvk) (disclaimer: I'm the author) where they need to be compatible so you can try to build clvk to get a compatible version of both tools.

Out of curiosity, what OpenCL SPIR-V producer are you trying to convert the output of? (Depending on what it is, there might be a better path.)

**Comment by fodinabor** [comment]
Yeah, just thought it would be awesome if it was possible to ingest OpenCL SPIR-V directly.

I'm currently playing around with https://github.com/intel/llvm trying to check-out whether it would be possible to run SYCL on Vulkan ;-)  
It's possible to generate LLVM-IR from it using `-fsycl-device-only`, but that seemed incompatible with clspv. I thought SPIR-V would be more stable.

But maybe I should try again to use the intel/llvm as LLVM code base for clspv, so that those to be compatible.

**Comment by kpet** [comment]
>I'm currently playing around with https://github.com/intel/llvm trying to check-out whether it would be possible to run SYCL on Vulkan ;-)

I've been looking at this as well. That's one of the reasons I added prototype support for cl_khr_il_program to clvk. The SPIR-V path is likely to be easier and more stable than trying to pass LLVM IR.

I haven't tried to get it to work end-to-end yet but all the building blocks should now be there. FWIW, I know someone who's run a few examples from another SYCL implementation on Vulkan using clvk/clspv already so it's definitely possible for basic programs.

**Comment by fodinabor** [comment]
Sounds awesome, I've been looking into making a native implementation, but I'll try clvk first asap :)

**Comment by kpet** [comment]
Great, feedback most welcome! Just so you know: I'm chasing a build system bug in LLVM that you might hit. If you want to guarantee that you won't hit it, please pass `-DLLVM_TARGETS_TO_BUILD=ARM` to CMake during the configuration as done in the automated tests (https://github.com/kpet/clvk/blob/master/tests/travis/step-script.sh).

**Comment by kpet** [comment]
The issue mentioned in my previous comment is now fixed.

**Comment by kpet** [comment]
Unless there is a plan to add support for consuming OpenCL SPIR-V to clspv that I'm not aware of, I suggest we close this issue.

@fodinabor Any objections?
