### ISSUE TITLE
Missing builtin? _Z11read_imageh

### ISSUE THREAD

**Issue by alex-xia-xia** [google/clspv#455]
Can't translate function call.  Missing builtin? _Z11read_imageh14ocl_image2d_ro11ocl_samplerDv2_i in:   %call38 = tail call spir_func <4 x half> @_Z11read_imageh14ocl_image2d_ro11ocl_samplerDv2_i(%opencl.image2d_ro_t.float.sampled addrspace(1)* %1, %opencl.sampler_t addrspace(2)* %32, <2 x i32> %33) #6
Can't translate function call.  Missing builtin? _Z11read_imageh14ocl_image2d_ro11ocl_samplerDv2_i in:   %call33 = tail call spir_func <4 x half> @_Z11read_imageh14ocl_image2d_ro11ocl_samplerDv2_i(%opencl.image2d_ro_t.float.sampled addrspace(1)* %1, %opencl.sampler_t addrspace(2)* %30, <2 x i32> %31) #6
Can't translate function call.  Missing builtin? _Z11read_imageh14ocl_image2d_ro11ocl_samplerDv2_i in:   %call28 = tail call spir_func <4 x half> @_Z11read_imageh14ocl_image2d_ro11ocl_samplerDv2_i(%opencl.image2d_ro_t.float.sampled addrspace(1)* %1, %opencl.sampler_t addrspace(2)* %28, <2 x i32> %29) #6
Can't translate function call.  Missing builtin? _Z11read_imageh14ocl_image2d_ro11ocl_samplerDv2_i in:   %call23 = tail call spir_func <4 x half> @_Z11read_imageh14ocl_image2d_ro11ocl_samplerDv2_i(%opencl.image2d_ro_t.float.sampled addrspace(1)* %1, %opencl.sampler_t addrspace(2)* %26, <2 x i32> %27) #6
Can't translate function call.  Missing builtin? _Z11read_imageh14ocl_image2d_ro11ocl_samplerDv2_i in:   %call18 = tail call spir_func <4 x half> @_Z11read_imageh14ocl_image2d_ro11ocl_samplerDv2_i(%opencl.image2d_ro_t.float.sampled addrspace(1)* %0, %opencl.sampler_t addrspace(2)* %24, <2 x i32> %25) #6
Can't translate function call.  Missing builtin? _Z11read_imageh14ocl_image2d_ro11ocl_samplerDv2_i in:   %call13 = tail call spir_func <4 x half> @_Z11read_imageh14ocl_image2d_ro11ocl_samplerDv2_i(%opencl.image2d_ro_t.float.sampled addrspace(1)* %0, %opencl.sampler_t addrspace(2)* %22, <2 x i32> %23) #6
Can't translate function call.  Missing builtin? _Z11read_imageh14ocl_image2d_ro11ocl_samplerDv2_i in:   %call8 = tail call spir_func <4 x half> @_Z11read_imageh14ocl_image2d_ro11ocl_samplerDv2_i(%opencl.image2d_ro_t.float.sampled addrspace(1)* %0, %opencl.sampler_t addrspace(2)* %20, <2 x i32> %21) #6
Can't translate function call.  Missing builtin? _Z11read_imageh14ocl_image2d_ro11ocl_samplerDv2_i in:   %call3 = tail call spir_func <4 x half> @_Z11read_imageh14ocl_image2d_ro11ocl_samplerDv2_i(%opencl.image2d_ro_t.float.sampled addrspace(1)* %0, %opencl.sampler_t addrspace(2)* %18, <2 x i32> %19) #6
Can't translate function call.  Missing builtin? _Z12write_imageh14ocl_image2d_woDv2_iDv4_Dh in:   tail call spir_func void @_Z12write_imageh14ocl_image2d_woDv2_iDv4_Dh(%opencl.image2d_wo_t.float addrspace(1)* %2, <2 x i32> %vecinit88, <4 x half> %c3.0.lcssa) #5
Can't translate function call.  Missing builtin? _Z12write_imageh14ocl_image2d_woDv2_iDv4_Dh in:   tail call spir_func void @_Z12write_imageh14ocl_image2d_woDv2_iDv4_Dh(%opencl.image2d_wo_t.float addrspace(1)* %2, <2 x i32> %vecinit83, <4 x half> %c2.0.lcssa) #5
Can't translate function call.  Missing builtin? _Z12write_imageh14ocl_image2d_woDv2_iDv4_Dh in:   tail call spir_func void @_Z12write_imageh14ocl_image2d_woDv2_iDv4_Dh(%opencl.image2d_wo_t.float addrspace(1)* %2, <2 x i32> %vecinit78, <4 x half> %c1.0.lcssa) #5
Can't translate function call.  Missing builtin? _Z12write_imageh14ocl_image2d_woDv2_iDv4_Dh in:   tail call spir_func void @_Z12write_imageh14ocl_image2d_woDv2_iDv4_Dh(%opencl.image2d_wo_t.float addrspace(1)* %2, <2 x i32> %vecinit73, <4 x half> %c0.0.lcssa) #5

**Comment by rjodinchr** [comment]
This builtin is now supported
