### ISSUE TITLE
Incorrect mapping of fmax/fmin

### ISSUE THREAD

**Issue by mantognini** [google/clspv#506]
Hi,

I've noticed that OpenCL C `fmax` function is mapped to GLSL SPIR-V `FMax` instruction. But the behaviour is not the same w.r.t. NaNs. Instead, I believe the `NMax` instruction could be used. Similarly, OpenCL C `fmin` is mapped to `FMin` instead of `NMin`.

For convenience, here are the various definitions:
##### OpenCL C `fmax(x, y)`
> Returns y if x < y, otherwise it returns x. If one argument is a NaN, fmax() returns the other argument. If both arguments are NaNs, fmax() returns a NaN.

##### GLSL SPIR-V `FMax`
> Result is y if x < y, either x or y when both x and y are zeros, otherwise x. Which operand is the result is undefined if one of the operands is a NaN.

##### GLSL SPIR-V `NMax`
> Result is y if x < y, either x or y when both x and y are zeros, otherwise x. If one operand is a NaN, the other operand is the result. If both operands are NaN, the result is a NaN.

I guess it doesn't help that the correct OpenCL SPIR-V instructions are `fmax` and `fmin`...

The following program can be used as input to test this.
```
kernel void kern(global float* x) {
  x[0] = fmin(x[1], x[2]);
  x[3] = fmin(x[1], x[2]);
}

**Comment by alan-baker** [comment]
FClamp -> NClamp still needs to be addressed.
