### ISSUE TITLE
vloadn/vstoren documentation 

### ISSUE THREAD

**Issue by mantognini** [google/clspv#507]
The [documentation](https://github.com/google/clspv/blob/master/docs/OpenCLCOnVulkan.md#vector-data-load-and-store-functions) says that vload and vstore built-in functions must not be used, yet clspv happily consumes those in my sample programs.

I suspect that those are not supported under all circumstances. Could someone clarify what is or isn't supported?

**Comment by kpet** [comment]
Quite a few cases are indeed supported now. FWIW, all the `basic:vload*` conformance tests are now passing (with 8- and 16-element vectors disabled in the tests) but `basic:vstore_{local,private}` are still failing.

**Comment by rjodinchr** [comment]
They are now supported
