### ISSUE TITLE
Reduce duplication of pointer types

### ISSUE THREAD

**Issue by dneto0** [google/clspv#52]
Example:
```
void foo(global uint* A, int n) {
  A[n] = n;
}

void bar(global uchar4 * A, int n) {
  A[n].x = (uchar)n;
}

kernel void goth(global uint *A, global uchar4 *B, int n) {
  foo(A, n);
  bar(B, n);
}
```
Produces two pointer-to-storage-buffer-of-runtime-array-of-32-bit-int types, each decorated with ArrayStride 4.
e.g.
```
               OpDecorate %_ptr_StorageBuffer_uint ArrayStride 4
               OpDecorate %_ptr_StorageBuffer_uint_0 ArrayStride 4
...
%_ptr_StorageBuffer_uint = OpTypePointer StorageBuffer %uint
...
%_ptr_StorageBuffer_uint_0 = OpTypePointer StorageBuffer %uint
```

This is slightly wasteful and could confuse older versions of the validator. (See https://github.com/KhronosGroup/SPIRV-Tools/pull/783)

It would be an enhancement if we could avoid generating two different pointer types in this case.

**Comment by rjodinchr** [comment]
This is not the case anymore
