### ISSUE TITLE
Report kernels with no arguments in the descriptor map?

### ISSUE THREAD

**Issue by kpet** [google/clspv#536]
From https://github.com/kpet/clvk/issues/23:

>clvk currently relies on the descriptor map obtained from clspv to ascertain the existence of a kernel in a given program. Kernels with no arguments aren't described at all in the descriptor map and thus can't be used (kernel creation will fail).

How would you feel about adding a new `kernelnoargs,<name>` type of entry to the descriptor map? This would arguably be an abuse of the descriptor map but one that doesn't feel too bad. Alternatively, clvk could parse the SPIR-V module to get the list of entrypoints but that's one more dependency on SPIRV-Tools that I'd rather avoid if possible.

**Comment by alan-baker** [comment]
Maybe better would be to add a list of entry points like:
```
entry_point,foo
entry_point,bar
```

Or possibly adding some depth to the descriptor map to have all kernel entries grouped under a kernel structure that streams like:
```
kernel_decl,foo
kernel,foo,arg,blah,...
...
kernel_decl,bar
...
```

The first is much simpler than the second.

**Comment by kpet** [comment]
I think I'd rather keep the descriptor map unordered as it's easier to parse. Since we're repeating the kernel name in existing entries, there's no strict need to group the entries apart from making this a bit more readable. Grouping would be useful to report other kernel-related information without repeating the name of the kernel though. I think I'd want to use the descriptor map to report the `reqd_work_group_size` as well for example but that can be done easily using `kernel,<name>,reqd_work_group_size,<val>`.

Agree that adding a parallel list of all kernels is cleaner. I'll have a stab at that and see what it looks like.
