### ISSUE TITLE
Assertion isa<BitCastOperator>(CI->getArgOperand(0)) failed

### ISSUE THREAD

**Issue by andreperezmaselco** [google/clspv#537]
Testing clspv, more specifically, on the commit hash `077517b940a2cc65edba2cdca93d3b023eff6b60`, the following error was logged in the terminal:

```
clspv: ./clspv/lib/ReplaceLLVMIntrinsicsPass.cpp:195: bool
{anonymous}::ReplaceLLVMIntrinsicsPass::replaceMemcpy(llvm::Module&): Assertion
`isa<BitCastOperator>(CI->getArgOperand(0))' failed.
Aborted (core dumped)
```

Debugging the clspv, I found that, at `ReplaceLLVMIntrinsicsPass::replaceMemcpy`,
`CI->getArgOperand(0)` and `CI->getArgOperand(1)` returns can be a `GEPOperator` instead of a `BitCastOperator`. So, some logic must be added to cover the `GEPOperator` case.

**Comment by rjodinchr** [comment]
I think this should be fixed now. Feel free to reopen if not
