### ISSUE TITLE
SplatArgPass hangs

### ISSUE THREAD

**Issue by jrprice** [google/clspv#541]
Clspv hangs in SplatArgPass for any kernel that triggers its functionality (we seem to be lacking test coverage for it?).

e.g.:
```
kernel void foo(global int4 *data, int value) {
  data[0] = min(data[0], value);
}
```

The cause seems to be [this loop](https://github.com/google/clspv/blob/04f3a95d01078d644f6ea9710061e3e0aac854d1/lib/SplatArgPass.cpp#L161-L163) introduced by #531, presumably because it updates the use list of the function inside the loop that iterates over it (instead of building a work list).

**Comment by sjw36** [comment]
I am investigating..

**Comment by sjw36** [comment]
Well I do see 54 tests exercising this code and your testcase does pass for me but I agree we shouldn't be adding to a list that we are iterating over. I will submit a fix.
