### ISSUE TITLE
Proposed refactor SPIRVProducerPass

### ISSUE THREAD

**Issue by sjw36** [google/clspv#545]
As a precursor to adding sub_groups instruction support I would like to refactor a bit of the SPIRVProducerPass as follows:

- Create SPIRV Module Sections for SPIRVInstructions according to 2.4 of the [spec](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#_a_id_logicallayout_a_logical_layout_of_a_module).
  - This removes the need for looking up and inserting OpDecorates
- Remove Constant collection and gather/insert on-the-fly
- Add a Builder class to create and insert new SPIRVInstructions, the only place to ++nextID based on spv::HasResultAndType.
- Create a placeholder for the DeferredInsts instead of capturing an insertion point
- Collect a set of capabilities on-the-fly, and generate list after all instructions generated.

Does this plan sound acceptable?

**Comment by sjw36** [comment]
BTW, it doesn't look like SPIRVProducerPass handles function declarations. Is there a reason? Seems like it may be needed for library support.

**Comment by alan-baker** [comment]
Still thinking about the proposal, answering the question:
>BTW, it doesn't look like SPIRVProducerPass handles function declarations. Is there a reason? 

SPIR-V requires that all function declarations be decorated with the Import Linkage Type. That, in turn, requires the Linkage capability, which Vulkan does not allow. Right now clspv isn't setup to do proper linking for libraries.

**Comment by sjw36** [comment]
That's all for now. I will create a new issue for sub_group support
