### ISSUE TITLE
vload_half3_* and vstore_half3_* are not supported

### ISSUE THREAD

**Issue by dneto0** [google/clspv#57]
This is not documented in the language mapping doc.

Supporting 3-element vectors in replace-pointer-bitcasts is complicated because remapping 3-element vector into a pointer-to-4-elem vector can span elements in the target array.

**Comment by dneto0** [comment]
Here's an example of the complexity I'm concerned about:

global float2* OUT;
float3 value = ...
vstore_half3(value, 1, (half*)OUT);

vstore_half3 says: 

> The floatn value given by data is converted
to a halfn value using the appropriate
rounding mode. The halfn value is then
written to address computed as (p + (offset
* n)). The address computed as (p + (offset
* n)) must be 16-bit aligned.
vstore_halfn uses the default rounding
mode. The default rounding mode is round
to nearest even.

In this case n = 3.  So we should be writing at least 48 bits of data (possibly 64 bits) starting at 48bits into  the OUT array.   Each OUT element is 64 bits wide, so that means we have to update two adjacent elements:  
 - the last 16 bits of element 0 of OUT
 - the first 32 bits (possibly 48 bits) of element 1 of OUT

**Comment by rjodinchr** [comment]
I think this is fixed now with the `ThreeElementVector` pass
