### ISSUE TITLE
Strange codegen for swizzle expressions

### ISSUE THREAD

**Issue by gnl21** [google/clspv#622]
I'm seeing code such as:
```
float4 a;
float c = a.x + a.y;
```
generating `OpVectorShuffle a, undef, [n, -1, -1, -1]`s for each of `a.x` and `a.y` (with the appropriate value of `n`), then doing a float4 add, and extracting the first component afterwards. Is this expected? I had expected to see extracts of the components and a single float add.

(I don't think that the code generated is actually _wrong_, but it seems verbose and somewhat inefficient for other tools to process).

**Comment by alan-baker** [comment]
This is LLVM being clever unfortunately. You can use `-disable-vector-combine` and get the code you expect.

**Comment by gnl21** [comment]
If this is the expected result then I guess that's fine and other tools will need to expect this anyway. It's not a difficult pattern to optimise, although it did show up a bug in our implementation which we've now fixed.
