### ISSUE TITLE
log1p not implemented

### ISSUE THREAD

**Issue by gnl21** [google/clspv#623]
The CL builtin function log1p is not currently implemented and is used in a kernel that I'm trying to compile. I've implemented the function in the obvious way as log(1+x) and was going to make a PR, but a couple of questions:
* The implementation matches the precision of fast-math, but it does sort of defeat the object of having this function in the first place. Do you want the function implemented in that way?
 * I found two places in the compiler where derived functions are implemented (ReplaceCLBuiltins and during SPIR-V code generation). Is there a reason to prefer one over the other? I see that, for example, log10 is implemented in replace builtins, while asinpi is implemented during code generation. (FWIW, my implementation is based on that of log10, but could easily be changed).

**Comment by sjw36** [comment]
ReplaceCLBuiltins is best for translating builtins to complex code that may need to be expanded or optimized further. The SPIRV code generation step should be for 1-to-1 translation from OpenCL Builtins to SPIRV intrinsics.

**Comment by gnl21** [comment]
OK, thanks for the information. It sounds like what I've done is OK then.
