### ISSUE TITLE
Invalid vector typecast with select operators

### ISSUE THREAD

**Issue by gnl21** [google/clspv#624]
When compiling the test kernel:
```
__kernel void ptr_cast_fail(float4 a, float4 b)
{
  float4 o = b > a ? a : (b <= a ? b : a);
}
```
I get a crash inside LLVM:
```
clspv: third_party/llvm/llvm/lib/IR/Instructions.cpp:2985: static llvm::CastInst* llvm::CastInst::CreatePointerCast(llvm::Value*, llvm::Type*, const llvm::Twine&, llvm::Instruction*): Assertion `S->getType()->isPtrOrPtrVectorTy() && "Invalid cast"' failed.
```
The problem does not occur if the vectors are switched for floats.

**Comment by mantognini** [comment]
Interesting timing, I came across a variant of this issue too and was about to create a PR. It seems my patch solves this crash.

**Comment by gnl21** [comment]
Excellent. I was planning on looking into it but I haven't had time yet, so the timing is perfect for me! Thanks.
