### ISSUE TITLE
segfault if kernel argument has type of pointer to unknown structure type

### ISSUE THREAD

**Issue by FROL256** [google/clspv#645]
Hi! Not critical issue, but i suppose to get error message "Lite_Hit is undefined" or something like that instead of segfault. 
```cpp
//struct Lite_Hit
//{
//  float t;
//  int   primId; 
//  int   instId;
//  int   geomId;
//};

static inline float3 make_float3(float a, float b, float c) 
{ 
  float3 res = {a,b,c}; 
  return res;
}

__kernel void kernel_TestColor(
  __global const struct Lite_Hit * restrict in_hit,
  __global float3 * restrict out_color,
  const uint iNumElements)
{
  /////////////////////////////////////////////////
  const uint tid = get_global_id(0);
  if (tid >= iNumElements)
    return;
  /////////////////////////////////////////////////

  float x = 2.0f;
  if(in_hit[tid].primId != -1)
    out_color[tid] = make_float3(1,1,1);
  else
    out_color[tid] = make_float3(0,0,0);
}
```
Thank you very much!

**Comment by FROL256** [comment]
Btw: i have just updated and rebuild clspv. It goes a bit better but still not as expected

clspv: ../third_party/llvm/clang/lib/AST/RecordLayoutBuilder.cpp:3181: const clang::ASTRecordLayout& clang::ASTContext::getASTRecordLayout(const clang::RecordDecl*) const: Assertion `D && "Cannot get layout of forward declarations!"' failed.

**Comment by kpet** [comment]
This looks like a duplicate of https://github.com/google/clspv/issues/316

**Comment by FROL256** [comment]
Indeed, thank you!
