### ISSUE TITLE
Duplicate ArrayStride decorations generated

### ISSUE THREAD

**Issue by fused** [google/clspv#651]
```
float func1(__constant const float* arr)
{
	return arr[1];
}


float func2(const int N, __global const float* const arr)
{
	return arr[1] * N;
}


__kernel void kernel1(
	__constant const float* const restrict const_data,
	__global const float * const restrict data
)
{
	func1(&const_data[4]);
	func2(0, &data[4]);
}
```

spirv-val produces this error:

error: line 40: ID '15' decorated with ArrayStride multiple times is not allowed.
  %_ptr_StorageBuffer_float = OpTypePointer StorageBuffer %float

When the multiplication by N in func2 is removed, it gives this error instead:

error: line 45: Duplicate non-aggregate type declarations are not allowed. Opcode: TypeFunction id: 33
  %33 = OpTypeFunction %float %_ptr_StorageBuffer_float

**Comment by alan-baker** [comment]
Thanks for the report. FYI, the provided test ran successfully because none of the sub-results were used. Adding another buffer fixes that.

**Comment by alan-baker** [comment]
The core of the problem is that clspv is mapping both `__constant` and `__global` to `StorageBuffer`, but the LLVM IR uses different address spaces for those pointers. The resulting types are not properly disambiguated.

**Comment by fused** [comment]
Thank you.
