### ISSUE TITLE
mad_sat doesn't pass CTS on NVidia HW

### ISSUE THREAD

**Issue by kpet** [google/clspv#673]
The newly added mad_sat built-in function doesn't pass the OpenCL CTS on my machine (Nvidia GeForce GTX 1050 Ti, Linux driver 455.28). It seems to be an issue with the Vulkan driver, that AFAICT only affects ushort vectors.

```
integer_mad_sat...
ERROR: Data sample 243:0 does not validate! Expected (0xffff), got (0x43b8), sources (0x016b, 0x00ab, 0x513f)
   Vector ushort2,ushort2,ushort2 FAILED
integer_mad_sat FAILED
```

Looking at the failing case, it seem likely the culprit is `OpIAddCarry` not producing the carry value.

**Comment by alan-baker** [comment]
You should definitely file a bug with Nvidia if you haven't. For clspv, we could introduce another hack option or change the implementation to do the addition and compare the results similar to the signed case.

**Comment by alan-baker** [comment]
We should probably also file a bug for increased Vulkan CTS coverage of OpIAddCarry.

**Comment by kpet** [comment]
Agree on all points. I filed it here first to give visibility to other clspv users and see if you guys could reproduce it.

**Comment by alan-baker** [comment]
I tested this on a Quadro M2000 running driver 440.100 and it passed. Different architecture and slightly older driver, but another data point.

**Comment by kpet** [comment]
It seems recent drivers have fixed this, tentatively closing. Feel free to reopen if you think we should consider adding a workaround for broken drivers.
