### ISSUE TITLE
After specialization was applied VkShaderModule does not contain valid spirv for stage VK_SHADER_STAGE_COMPUTE_BIT

### ISSUE THREAD

**Issue by FROL256** [google/clspv#677]
Hi! Please excuse me for such newbie question.

I have applied spec. constant to set work group size and my kernel actually works correct. 
But Validation layer claims i did some thing wrong after vkCreateComputePipelines.

Here is my command line the output:
FindPhysicalDevice: {  device 0, name = GeForce RTX 2080 <-- (selected)}

VUID-VkPipelineShaderStageCreateInfo-module-parameter(ERROR / SPEC): msgNum: -42869648 - Validation Error: [ VUID-VkPipelineShaderStageCreateInfo-module-parameter ] Object 0: handle = 0x555555baec80, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xfd71dc70 | After specialization was applied, VkShaderModule 0xc000000000c[] does not contain valid spirv for stage VK_SHADER_STAGE_COMPUTE_BIT. The Vulkan spec states: module must be a valid VkShaderModule handle (https://vulkan.lunarg.com/doc/view/1.2.148.0/linux/1.2-extensions/vkspec.html#VUID-VkPipelineShaderStageCreateInfo-module-parameter)
    Objects: 1
        [0] 0x555555baec80, type: 3, name: NULL

Here is my code for spec constants:

 `
  VkSpecializationMapEntry specializationEntries[3] = {};
  {
    specializationEntries[0].constantID = 0;
    specializationEntries[0].offset     = 0;
    specializationEntries[0].size       = sizeof(uint32_t);

    specializationEntries[1].constantID = 1;
    specializationEntries[1].offset     = sizeof(uint32_t);
    specializationEntries[1].size       = sizeof(uint32_t);

    specializationEntries[2].constantID = 2;
    specializationEntries[2].offset     = 2 * sizeof(uint32_t);
    specializationEntries[2].size       = sizeof(uint32_t);
  }
  uint32_t specializationData[3] = {16, 16, 1};
  VkSpecializationInfo specsForWGSIze = {};
  {
    specsForWGSIze.mapEntryCount = 3;
    specsForWGSIze.pMapEntries   = specializationEntries;
    specsForWGSIze.dataSize      = 3 * sizeof(uint32_t);
    specsForWGSIze.pData         = specializationData;
  }
`

Here is my disassembled SPIR-V [z_spirv.txt](https://github.com/google/clspv/files/5585789/z_spirv.txt)

Probably i did some-thing wrong ...  thank you very much!

**Comment by FROL256** [comment]
I have checked same C++ code with GLSL/glsVangValidator and there were no analogue messages from validation layers. 

`
#version 440

layout(local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2) in;

layout(std430, binding = 0) buffer layout0 { uint flags[]; };
layout(std430, binding = 1) buffer layout1 { uint rayPosAndNear[]; };
layout(std430, binding = 2) buffer layout2 { uint rayDirAndFar[]; };
layout(std430, binding = 3) buffer layout3 { uint kgen_data[]; };

uint fakeOffset (uint x, uint y) { return y*512 + x; } 

layout( push_constant ) uniform params_t
{
  uint sizeX;
  uint sizeY;
} params;


void main() 
{
  flags[fakeOffset(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y)] = 1;
}

`
[z_test.comp.txt](https://github.com/google/clspv/files/5588978/z_test.comp.txt)

I would appreciate for any comment, probably  i can just ignore validation layer message ... ) Thank you!

**Comment by alan-baker** [comment]
It looks ok to me using the latest validator code. Did the validation layers report the actual validator error message? The one you copied just says the module is invalid.

**Comment by FROL256** [comment]
Sorry, i didn't understand the answer. 

I have enabled two validation layers (well, because in the beginning it was LUNARG and later KHRONOS and on different machines i had different SDK versions previously) :
"VK_LAYER_KHRONOS_validation"
"VK_LAYER_LUNARG_standard_validation"

I have checked them separately, but there is no difference.

Right after execution of vkCreateComputePipelines i got this output in command line:

VUID-VkPipelineShaderStageCreateInfo-module-parameter(ERROR / SPEC): msgNum: 0 - After specialization was applied, VkShaderModule 0xc000000000c[] does not contain valid spirv for stage VK_SHADER_STAGE_COMPUTE_BIT. The Vulkan spec states: module must be a valid VkShaderModule handle (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkPipelineShaderStageCreateInfo-module-parameter)
    Objects: 1
        [0] 0, type: 0, name: NULL

I didn't register any special callback, so, i thought this was an actual message from validation layer )
In this is not, could you please explain how to get the right one.

Right after vkCreateComputePipelines shader module will be destroyed with vkDestroyShaderModule and never used again, so, i suppose this is not a problem.

Thanks!

**Comment by alan-baker** [comment]
Try running the following using the spirv-opt and spirv-val from your SDK.
```
spirv-opt --set-spec-const-default-value "0:16 1:16 2:1" --freeze-spec-const z_spirv.spv -o opt.spv
spirv-val --target-env vulkan1.0 opt.spv
```

Does spirv-val give you an error message? I don't see an error using the top-of-tree spirv-tools, but it's worth trying with your specific version. If there is no error, then it is likely the way you are specializing the shader module itself via the Vulkan API.

**Comment by FROL256** [comment]
Thank you very much! I got this:

`
error: line 156: ID 39[%39] has not been defined
  %399 = OpExtInst %void %397 1 %39 %398
`
My SPIR-V tools version output is: SPIRV-Tools v2020.4 unknown hash, 2020-07-27T20:19:47
Updated disam: [z_spirv.txt](https://github.com/google/clspv/files/5622730/z_spirv.txt)

I put everything to google drive https://drive.google.com/file/d/1-BF8b5EHd3LPwww4hNkSAdaG5o-UCFiR/view?usp=sharing 

Let me update clspv an check it again to be sure problem is still there.

**Comment by FROL256** [comment]
1) Just have updated clspv, commit e0406e7..96bd3d9
2) Build with ./clspv z_generated.cl -o z_generated.cl.spv -pod-pushconstant (you may take z_generated.cl  and includes on google drive)

3) spirv-opt --set-spec-const-default-value "0:16 1:16 2:1" --freeze-spec-const z_spirv.spv -o opt.spv
4) spirv-val --target-env vulkan1.0 opt.spv
  and got 
`error: line 156: ID 39[%39] has not been defined
  %399 = OpExtInst %void %397 1 %39 %398
`
Validation layer in Vulkan report same error to me.

**Comment by alan-baker** [comment]
That is a bug in the SPIRV-Tools optimizer that has since been fixed (on Aug 13). The good news is, it should safe to ignore that validation error. The driver is likely handling the specialization differently than the validation layers. It should go away if you update to the latest Vulkan SDK.

**Comment by FROL256** [comment]
Great! Alan, thank you very much!
