### ISSUE TITLE
padding size of struct with 12 bytes to alignment boundary

### ISSUE THREAD

**Issue by FROL256** [google/clspv#688]
Greetings! I have found that clspv use strange alignment for structures with float3.  For example

`
typedef struct MaterialT 
{
  float3 color;
  uint   flags;
} SphereMaterial;
`
gives me warning: padding size of 'struct MaterialT' with 12 bytes to alignment boundary.

So, in fact size of structure became ... 32 bytes. This is quite strange for me, i would expect 16 bytes.
I tried to use _attribute__((aligned (4))) for struct or fields but didn't succeeded (well, clspv ignores __attribute__((packed)), ok). 

Is there any way to force aligment to 4 bytes in this case? 

Many thanks!

**Comment by alan-baker** [comment]
The `packed` attribute prevents adding the padding at the end of the struct. So the array stride would only be 20 bytes instead of 32 bytes. There is no way to pack `flags` at the end `color` as LLVM does not support laying structs out in that manner. To achieve that you would need to use a `float4` value and use `as_uint` on the fourth element.

**Comment by FROL256** [comment]
Thank you very much for the answer! 
I already did this trick and it helps. 

If this is not hard, could you please explain a bit more about "does not support laying structs out in that manner."
Does this mean that float3 is considered as a special type by LLVM which should be mapped to float4-like register?

For example, i don't have such problem with this code
`typedef struct MyFloat3T
{
  float x,y,z;
} MyFloat3;

typedef struct MaterialT
{
  MyFloat3 color;
  unsigned int flags;
} SphereMaterial;`

I also saw you issue about vec3 pointer casts https://github.com/google/clspv/issues/679 and think that may be they are related.

Please don't think that I am asking you to implement such packing, this is up to you anyway and particular for me this is not so critical. But let me explain my position of why neither 20 bytes, nor 32 bytes can be considered as expected value by users.

1) Such structures are very common for existing OpenCL/C++ code (especially in C++ where unions with float4 used very often).  
When you fill it on the CPU side with 16 bytes and than the read on GPU as if it is 20 bytes, well ... )

2) AFAIK, most modern GPU (ok, most Desktop GPUs) have scalar 32 bit registers for single thread/lane and thus packing data to float4 is almost useless for them. However, aligment for the whole structure is useful because we can read the whole structure with single instruction and than use 4 separate registers. I'm not sure how this could be mapped in SPIR-V, but this seems to me quite strange if it cannot be.

3) If my example with custom float3 works, may be you can do same inside clspv by just feeding to it different declaration of float3. Well, exclude it from special types and process as normal struct. Of course i suppose this has sence only if we still can guarantee single instruction for loading aligned data type in SPIR-V (or for target GPU architecture if we know it will optimize SPIR-V in appropriate way). Other way, performance is more important than comparability i suppose.

I would be interested to know what you think about it, thanks!

**Comment by alan-baker** [comment]
When LLVM and clang lay out structs, they use the alloc size to determine where to put the next element. A 3-element vector has the same alignment as a 4-element vector so for `MaterialT`, the `flags` member gets an offset of 16. If you look at cl_platform.h, you'll notice that cl_uint3 (for example) is just a typedef of cl_uint4. So usage on the host would match what the compiler is generating.

**Comment by FROL256** [comment]
Understood, thank you very much!
