### ISSUE TITLE
Sampler missing from entry point interface when used inside helper function

### ISSUE THREAD

**Issue by jrprice** [google/clspv#753]
When targeting SPIR-V 1.4+, Clspv does not add samplers used inside helper functions to the entry point interface, which causes spirv-val errors.

Example shader:
```
const sampler_t s = CLK_NORMALIZED_COORDS_FALSE | CLK_FILTER_NEAREST |
                    CLK_ADDRESS_CLAMP_TO_EDGE;

float4 bar(read_only image3d_t input) {
  return read_imagef(input, s, (int4)(0, 0, 0, 0));
}

kernel void foo(read_only image3d_t input) {
  bar(input);
}
```

Compiled with: `bin/clspv foo.cl -spv-version 1.4`

spir-val error:
```
error: line 40: Interface variable id <3> is used by entry point 'foo' id <23>, but is not listed as an interface
  %3 = OpVariable %_ptr_UniformConstant_1 UniformConstant
```

**Comment by kpet** [comment]
Hmm, https://github.com/google/clspv/pull/748 should have fixed this. Did it miss some cases or do you not have the change in your tree?

**Comment by jrprice** [comment]
I'm testing with ToT. At a glance, it looks like the code added in #748 does not account for the case where the sampler is used by a helper function and never referenced by the kernel function itself.

**Comment by kpet** [comment]
Right, I did test a case with a helper function but I think I was passing the sampler as an argument. We can either add all samplers to all entry points or look at the call tree.
