### ISSUE TITLE
difference between clspv and clang+llvm-spirv ?

### ISSUE THREAD

**Issue by duchao713** [google/clspv#759]
Hi,

I'm new with clspv. I have a short question:

What's the difference between clspv and clang+llvm-spirv(https://github.com/KhronosGroup/SPIRV-LLVM-Translator) ?

They both can convert .cl file to .spv

**Comment by AnastasiaStulova** [comment]
clspv allows targeting Vulkan compute i.e. it generates SPIR-V binary that can be injected by the Vulkan runtime. But llvm-spirv generates SPIR-V binary for OpenCL runtime.

FYI you can find more details in the OpenCL-Guide https://github.com/KhronosGroup/OpenCL-Guide/blob/main/chapters/os_tooling.md.

**Comment by duchao713** [comment]
Thanks a lot. Actually I had realized the difference after I asked. :)
