### ISSUE TITLE
CTS: basic: vstore_local: char8: issue with GEP and long vector

### ISSUE THREAD

**Issue by rjodinchr** [google/clspv#780]
Some tests of the CTS (`vstore_local`, `vload_local` and others) fail when trying with long vector type (ie. more than 4 elements).

In _Release_ mode, it _segfault_ in `Type.h`, coming from `SimplifyPointerBitcastPass.cpp:295`
In _Debug_, it hits an assert in `Instructions.h` also coming from `SimplifyPointerBitcastPass.cpp:295`

At that point clspv is trying to merge two GEPs (one being the input of the other).
The initial pointer is a pointer on a long vector, which has been lower to a pointer on a structure.
The line in `SimplifyPointerBitcastPass` is trying to create the new GEP which will be the merge of the two GEPs.

In this case, the GEP, is trying to point on a element inside the structure.

When llvm is making this GEP, it needs to know the return type of this GEP. The pointer being a structure, it tries to know which element of the structure is targeted, but the Idx is dynamic in this case, thus, it is impossible to know which element of the structure is targeted. At the end, llvm consider the index as invalid for the structure, and return a null pointer as the return type of the GEP, which produces the errors mentioned above.

**Comment by rjodinchr** [comment]
Would having long vectors being lower to arrays instead of structures fix this issue? @kpet ?

**Comment by alan-baker** [comment]
One thing to watch out for is when combined with #776 the compiler will not be able to use push constants for POD arguments that were long vectors. Vulkan has a restriction that clspv can't guarantee that any array in a push constant is only accessed with dynamically uniform indices.
