### ISSUE TITLE
Pointer types missing from bitcast instructions with opaque pointers support

### ISSUE THREAD

**Issue by omarahmed1111** [google/clspv#916]
Some passes like `ThreeElementVectorLoweringPass` depend on the pointer bitcasts instruction inside the IR module. After opaque pointer transition, all pointer bitcasts are trivial and will not likely be generated by clang. 

Example for a kernel for this:
```
kernel void test(global int3 *in) {
  (global int *)in;
}
```

This will generate this IR with opaque pointer support:
```
@__spirv_WorkgroupSize = addrspace(8) global <3 x i32> zeroinitializer

; Function Attrs: convergent norecurse nounwind
define dso_local spir_kernel void @test(ptr addrspace(1) align 16 %in) #0 !kernel_arg_addr_space !4 !kernel_arg_access_qual !5 !kernel_arg_type !6 !kernel_arg_base_type !7 !kernel_arg_type_qual !8 !clspv.pod_args_impl !9 {
entry:
  %in.addr = alloca ptr addrspace(1), align 4
  store ptr addrspace(1) null, ptr %in.addr, align 4
  store ptr addrspace(1) %in, ptr %in.addr, align 4
  %0 = load ptr addrspace(1), ptr %in.addr, align 4
  ret void
}
```

which contains no information about the int* cast, if we add a use for the cast, we might be able to infer the types from analysing the instructions but it is not simple and it is only when there is a usage that does not involve pointers. 

Is there a plan of how this pointer casts will be handled?

**Comment by rjodinchr** [comment]
I feel like I am missing some knowledge about what has been done in `ReplacePointerBitcastPass` and `LongVectorLoweringPass` to answer.
So take my words with caution.
For `ThreeElementVectorLoweringPass` I think the real thing to detect is where an argument is infer as vec3, but has access in the function as something different (a scalar, or just a different vector type). If this is the case, then it is important not to declare the argument as a vec3, as it can lead to issue with the code trying to access the fourth (unexisting) element of a vec3, which is just not possible in SPIRV.

**Comment by omarahmed1111** [comment]
That make sense of why the bitcast was there and how to work around its removal. Thanks for the information.

**Comment by alan-baker** [comment]
Is this issue still necessary now that three-element vector lowering is transitioned?

**Comment by omarahmed1111** [comment]
I added it originally for `ThreeElementVectorLoweringPass` so I think it is not needed for now. maybe in the future if that problem appears with another pass, someone could reopen it. But, I think it could be closed for now
