### ISSUE TITLE
/usr/include/stdlib.h:32:10: fatal error: 'stddef.h' file not found

### ISSUE THREAD

**Issue by MajidAbdelilah** [google/clspv#991]
hey i have a problem i have compiled clspv from source code on arch linux and i have triyed to compile a project with it 
this is the compile command: ``` clspv -O3 test.c -o test_gpu.spv ```
and this is the output: ```  In file included from test.c:1:
/usr/include/stdlib.h:32:10: fatal error: 'stddef.h' file not found
#include <stddef.h>
                   ^~~~~~~~~~ ```
i have llvm installed and also clang and llvm-libs too

**Comment by rjodinchr** [comment]
Hi,
It is because `clspv` is an `OpenCL-C` compiler. Which means that it needs to be given a `OpenCL-C` source code as input to be able to compile it to `SPIR-V`.
[Here](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_C.html) is the `OpenCL-C` specification.
Note that the C standard library is not part of the `OpenCL-C` language, thus including `stddef.h` or `stdlib.h` is not possible.

**Comment by MajidAbdelilah** [comment]
oh i am so sorry for my stupidness 
can you guide me to a tutorial for the opencl c language i would love to learn such a thing and also is using this will have better performance than using avx or avx2

**Comment by rjodinchr** [comment]
For an OpenCL tutorial, just google it and you shall find everything you need.

About avx, OpenCL and avx are different in many ways, but have 1 common point:
- OpenCL is a programming language, specialized for parallel computing. Most of the time, it is used to offload workload onto a co-processor specialized for parallel computing (GPU, FPGA, DSP, etc).
- avx are instructions of Intels and AMDs processors.
- As OpenCL, avx instructions (advanced vector instructions) are used for parallel workloads. avx instructions are SIMD instructions (single instruction multiple data). Most processors programmed through OpenCL make an intense use of SIMD instructions as well.

I am closing this issue as this is not about `clspv`.
