### ISSUE TITLE
Weird binding index of POD when using __local parameter and '--pod-ubo'

### ISSUE THREAD

**Issue by byzin** [google/clspv#992]
HI, it looks wrong binding index is assigned to POD when using __local parameter and '--pod-ubo' option.

The issue happens with following simple kernels (`kernels.cl`),
```
__kernel void localTest1Kernel(__global int* output,
                               __local int* storage1,
                               const int value1)
{
  const int id = get_global_linear_id();
  if (id == 0) {
    storage1[0] = value1;
    output[0] = storage1[0];
  }
}

__kernel void localTest2Kernel(__global int* output,
                               __local int* storage1,
                               __local int* storage2,
                               const int value1,
                               const int value2)
{
  const int id = get_global_linear_id();
  if (id == 0) {
    storage1[0] = value1;
    storage2[0] = value2;
    output[0] = storage1[0] + storage2[0];
  }
}
```
There are two kernels which use local and POD parameters.
And I compiled the kernels with '--pod-ubo' option,
```
clspv --pod-ubo -o test kernels.cl
clspv-reflection -o map.csv test
```
and I got a descriptor map (map.csv),
```
pushconstant,name,global_size,offset,0,size,12
pushconstant,name,region_offset,offset,16,size,12
kernel_decl,localTest1Kernel
kernel,localTest1Kernel,arg,output,argOrdinal,0,descriptorSet,0,binding,0,offset,0,argKind,buffer
kernel,localTest1Kernel,arg,storage1,argOrdinal,1,argKind,local,arrayElemSize,4,arrayNumElemSpecId,3
kernel,localTest1Kernel,arg,value1,argOrdinal,2,descriptorSet,0,binding,1,offset,0,argKind,pod_ubo,argSize,4
kernel_decl,localTest2Kernel
kernel,localTest2Kernel,arg,output,argOrdinal,0,descriptorSet,0,binding,0,offset,0,argKind,buffer
kernel,localTest2Kernel,arg,storage1,argOrdinal,1,argKind,local,arrayElemSize,4,arrayNumElemSpecId,3
kernel,localTest2Kernel,arg,storage2,argOrdinal,2,argKind,local,arrayElemSize,4,arrayNumElemSpecId,4
kernel,localTest2Kernel,arg,value1,argOrdinal,3,descriptorSet,0,binding,2,offset,0,argKind,pod_ubo,argSize,4
kernel,localTest2Kernel,arg,value2,argOrdinal,4,descriptorSet,0,binding,2,offset,4,argKind,pod_ubo,argSize,4
spec_constant,workgroup_size_x,spec_id,0
spec_constant,workgroup_size_y,spec_id,1
spec_constant,workgroup_size_z,spec_id,2
```
please look at 11,12 lines. The binding index of PODs of localTest2Kernel is 2. I suppose the index is 1 is expected.

I confirmed the issue doesn't happen when I don't use __local parameters (please see `kernels_pod.cl` and `map_pod.csv`).

here is the clspv I used,
clspv commit: 83055c38842e19d4dd45dc1812e88570a10f8598

here is the source files and descriptor maps,
[files.zip](https://github.com/google/clspv/files/10312850/files.zip)

Thanks

**Comment by rjodinchr** [comment]
Hi,

I am not very familiar with this part of `clspv`, but it seems that using `-distinct-kernel-descriptor-sets` gives the behaviour you are expecting.

I think (not sure at all) that the behaviour there is the expected one:
- https://github.com/google/clspv/blob/main/lib/SPIRVProducerPass.cpp#L1087
- https://github.com/google/clspv/blob/main/lib/AllocateDescriptorsPass.cpp#L205
- https://github.com/google/clspv/blob/main/lib/AllocateDescriptorsPass.cpp#L336
- https://github.com/google/clspv/blob/main/docs/OpenCLCOnVulkan.md#kernels

Also for next time, make sure that the command to reproduce actually works (`clspv --pod-ubo -o test kernels.cl -cl-std=CL2.0 -inline-entry-points` was needed on my side).

**Comment by byzin** [comment]
Hi @rjodinchr, I apologize the incomplete command I wrote.
Yeah `std=CL2.0 -inline-entry-points` is needed.

Actually wihtout `-distinct-kernel-descriptor-sets` is better for my program.
The issue is the behaviour of binding assignment is different between with and withour __local parameters.

`map.csv` line11,12 (compiled from `kernels.cl`),
```
kernel,localTest2Kernel,arg,value1,argOrdinal,3,descriptorSet,0,binding,2,offset,0,argKind,pod_ubo,argSize,4
kernel,localTest2Kernel,arg,value2,argOrdinal,4,descriptorSet,0,binding,2,offset,4,argKind,pod_ubo,argSize,4
```
`map_pod.csv` line8,9 (compiled from `kernels_pod.cl`),
```
kernel,podTest2Kernel,arg,value1,argOrdinal,1,descriptorSet,0,binding,1,offset,0,argKind,pod_ubo,argSize,4
kernel,podTest2Kernel,arg,value2,argOrdinal,2,descriptorSet,0,binding,1,offset,4,argKind,pod_ubo,argSize,4
```

`binding,1` without __local parameters, but `binding,2` with __local parameters.
I think __local parameters shouldn't affect the binding so `binding,1` is expected.

Thanks.

**Comment by rjodinchr** [comment]
@alan-baker would have a better knowledge about that, but my understanding when I read the links I gave you is that when a resource is used by all kernels, it will have the same binding for every kernels.
But when it differs each kernel will get a different one.

In your example, the local parameters differ between the two kernels, thus one is getting the binding 1 and the other binding 2.

It feels like you are trying to guess the binding without looking at the generated SPIRV code produced by `clspv`. I think you should parse the SPIRV code to know what bindings have been chosen by `clspv` and use those. It is what `clvk` is doing as far as I know.

**Comment by byzin** [comment]
Hi @rjodinchr, thank you for the suggestion. I'll take a look at the generated SPIR-V code.

**Comment by byzin** [comment]
Hi sorry for my late reply.
I did spirv-dis and checked the bindings in the spirv files.

kernels,
```
               OpDecorate %17 DescriptorSet 0
               OpDecorate %17 Binding 0
               OpDecorate %21 DescriptorSet 0
               OpDecorate %21 Binding 1
               OpDecorate %25 DescriptorSet 0
               OpDecorate %25 Binding 2
```

kernels_pod
```
               OpDecorate %17 DescriptorSet 0
               OpDecorate %17 Binding 0
               OpDecorate %21 DescriptorSet 0
               OpDecorate %21 Binding 1
               OpDecorate %25 DescriptorSet 0
               OpDecorate %25 Binding 1
```
`%17` is `__global int* output` and `%21` is pod struct in the first kernel `localTest1Kernel` and `%25` is pod struct in the second kernel `localTest2Kernel`.
So actually `%17` and `%25` have binding 1 and 2 respectively with local variables and have same binding 1 without local variables.
Can the binding rule be changed with and without local variables? If it's expected, I can close the ticket.

I attached the whole spirv-dis texts,
[spirv-dis-txt.zip](https://github.com/google/clspv/files/10526140/spirv-dis-txt.zip)

Thanks,

**Comment by rjodinchr** [comment]
I think this is the expected behavior

**Comment by byzin** [comment]
Thanks. Let me close the ticket.
